import { test, expect } from '@playwright/test';
import { URLS } from '../helpers/session';
test.skip(process.env.E2E_SHOPPING_FIXTURE!=='1','Uses mocked AI and catalog fixture.');
test.beforeEach(async({page})=>{await page.addInitScript(()=>localStorage.setItem('xiii_seller_access','fixture'));});
test('AI result is reviewed before staging, survives reload and retains correct SKU and form',async({page})=>{
 let createCalls=0,acceptCalls=0,productWrites=0;let status='QUEUED';
 await page.route('**/qa-ai-layer.svg',route=>route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="360" height="620"><path d="M154 172L128 182L108 222L129 237L140 222L139 315Q180 325 221 315L220 222L231 237L252 222L232 182L206 172Q180 190 154 172Z" fill="#292734"/><text x="168" y="223" fill="white" font-size="9">TEST</text></svg>'}));
 const job={id:'test-ai-job',variantId:'qa-product-0-M',form:'neutral',sourceUrl:URLS.seller+'/outfit/guide-neutral.svg',outputUrl:URLS.seller+'/qa-ai-layer.svg',error:''};
 await page.route('**/seller/products/qa-product-0/ai-artwork**',async route=>{const url=route.request().url();if(url.endsWith('/availability'))return route.fulfill({json:{success:true,data:{enabled:true,supported:true,reason:'',dailyLimit:10}}});if(url.endsWith('/review')){acceptCalls++;expect(route.request().postDataJSON().decision).toBe('ACCEPT');return route.fulfill({json:{success:true,data:{...job,status:'READY'}}});}if(route.request().method()==='POST'){createCalls++;expect(route.request().postDataJSON()).toMatchObject({variantId:job.variantId,form:job.form});return route.fulfill({json:{success:true,data:{...job,status}}});}return route.fulfill({json:{success:true,data:{...job,status}}});});
 await page.route('**/seller/products/qa-product-0',async route=>{if(route.request().method()==='PATCH'){productWrites++;return route.fulfill({json:{success:true,data:{_id:'qa-product-0',status:'DRAFT'}}});}return route.continue();});
 await page.goto(URLS.seller+'/products/qa-product-0');await page.getByRole('button',{name:'Tạo áo bằng AI',exact:true}).click();await expect(page.getByLabel('SKU mặc thử',{exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Lưu thông tin',exact:true})).toBeDisabled();expect(createCalls).toBe(1);status='READY';await expect(page.getByRole('button',{name:'Dùng ảnh AI cho SKU này',exact:true})).toBeVisible();await expect(page.getByLabel('URL artwork mặc thử',{exact:true})).toHaveValue('');await expect(page.getByRole('button',{name:'Dùng ảnh AI cho SKU này',exact:true})).toBeDisabled();expect(productWrites).toBe(0);
 await page.reload();await expect(page.getByAltText('Ảnh gốc SKU gửi AI')).toBeVisible();expect(createCalls).toBe(1);await page.getByRole('checkbox',{name:/Tôi đã kiểm tra/}).check();await page.getByRole('button',{name:'Dùng ảnh AI cho SKU này',exact:true}).click();await expect(page.getByLabel('URL artwork mặc thử',{exact:true})).toHaveValue(job.outputUrl);expect(acceptCalls).toBe(1);expect(productWrites).toBe(0);await page.screenshot({path:'docs/qa/v17/ai-seller-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.locator('.seller-ai-artwork').scrollIntoViewIfNeeded();await page.screenshot({path:'docs/qa/v17/ai-seller-mobile.png',fullPage:false});
});
test('disabled AI explains configuration and cannot submit paid job',async({page})=>{
 let writes=0;await page.route('**/ai-artwork**',route=>{if(route.request().method()==='POST')writes++;return route.fulfill({json:{success:true,data:{enabled:false,supported:true,reason:'AI chưa bật trên máy chủ; cấu hình khoá API và kho ảnh.',dailyLimit:10}}});});await page.goto(URLS.seller+'/products/qa-product-0');await expect(page.locator('.seller-ai-artwork')).toContainText('AI chưa bật');await expect(page.getByRole('button',{name:'Tạo áo bằng AI',exact:true})).toHaveCount(0);expect(writes).toBe(0);
});
test('AI failure unlocks editing without changing artwork or automatically creating another job',async({page})=>{
 let calls=0;await page.route('**/ai-artwork**',route=>{if(route.request().url().endsWith('/availability'))return route.fulfill({json:{success:true,data:{enabled:true,supported:true,dailyLimit:10}}});if(route.request().method()==='POST')calls++;return route.fulfill({json:{success:true,data:{id:'failed-job',variantId:'qa-product-0-M',form:'neutral',status:'FAILED',error:'Ảnh AI chưa đúng khung.',outputUrl:'',sourceUrl:''}}});});await page.goto(URLS.seller+'/products/qa-product-0');await page.getByRole('button',{name:'Tạo áo bằng AI',exact:true}).click();await expect(page.locator('.seller-ai-artwork [role=alert]')).toContainText('chưa đúng khung');await expect(page.getByLabel('SKU mặc thử',{exact:true})).toBeEnabled();await expect(page.getByLabel('URL artwork mặc thử',{exact:true})).toHaveValue('');expect(calls).toBe(1);await expect(page.getByRole('button',{name:'Tạo lượt AI mới',exact:true})).toBeEnabled();
});
test('unloadable AI preview cannot be accepted even though mannequin falls back to generic illustration',async({page})=>{
 await page.route('**/missing-ai.png',route=>route.fulfill({status:404,body:'missing'}));
 await page.route('**/ai-artwork**',route=>route.fulfill({json:{success:true,data:route.request().url().endsWith('/availability')?{enabled:true,supported:true,dailyLimit:10}:{id:'broken-job',variantId:'qa-product-0-M',form:'neutral',status:'READY',error:'',outputUrl:URLS.seller+'/missing-ai.png',sourceUrl:URLS.seller+'/outfit/guide-neutral.svg'}}}));
 await page.goto(URLS.seller+'/products/qa-product-0');await page.getByRole('button',{name:'Tạo áo bằng AI',exact:true}).click();await expect(page.locator('.seller-ai-artwork [role=alert]')).toContainText('Không tải được ảnh AI');await expect(page.getByRole('checkbox',{name:/Tôi đã kiểm tra/})).toBeDisabled();await expect(page.getByRole('button',{name:'Dùng ảnh AI cho SKU này',exact:true})).toBeDisabled();await expect(page.getByLabel('URL artwork mặc thử',{exact:true})).toHaveValue('');
});
test('recovery network error keeps saved job and blocks a new paid request until rechecked',async({page})=>{
 let reads=0,writes=0;await page.addInitScript(()=>localStorage.setItem('xiii-ai-artwork:qa-product-0:qa-product-0-M:neutral','saved-job'));
 await page.route('**/ai-artwork**',route=>{if(route.request().url().endsWith('/availability'))return route.fulfill({json:{success:true,data:{enabled:true,supported:true,dailyLimit:10}}});if(route.request().method()==='POST')writes++;if(++reads===1)return route.fulfill({status:503,json:{success:false,message:'Temporary network failure'}});return route.fulfill({json:{success:true,data:{id:'saved-job',variantId:'qa-product-0-M',form:'neutral',status:'READY',error:'',outputUrl:URLS.seller+'/outfit/guide-neutral.svg',sourceUrl:URLS.seller+'/outfit/guide-neutral.svg'}}});});
 await page.goto(URLS.seller+'/products/qa-product-0');await expect(page.locator('.seller-ai-artwork [role=alert]')).toContainText('Chưa tải được yêu cầu đã lưu');await expect(page.getByRole('button',{name:'Tạo áo bằng AI',exact:true})).toBeDisabled();expect(await page.evaluate(()=>localStorage.getItem('xiii-ai-artwork:qa-product-0:qa-product-0-M:neutral'))).toBe('saved-job');await page.getByRole('button',{name:'Kiểm tra yêu cầu AI',exact:true}).click();await expect(page.getByRole('checkbox',{name:/Tôi đã kiểm tra/})).toBeEnabled();expect(writes).toBe(0);
});
test('job belonging to another SKU or form is never rendered or staged as the current choice',async({page})=>{
 await page.route('**/ai-artwork**',route=>route.fulfill({json:{success:true,data:route.request().url().endsWith('/availability')?{enabled:true,supported:true,dailyLimit:10}:{id:'wrong-job',variantId:'qa-product-0-L',form:'feminine',status:'READY',outputUrl:URLS.seller+'/outfit/guide-feminine.svg',sourceUrl:''}}}));
 await page.goto(URLS.seller+'/products/qa-product-0');await page.getByRole('button',{name:'Tạo áo bằng AI',exact:true}).click();await expect(page.locator('.seller-ai-artwork [role=alert]')).toContainText('không đúng SKU');await expect(page.getByRole('button',{name:'Dùng ảnh AI cho SKU này',exact:true})).toHaveCount(0);await expect(page.getByLabel('URL artwork mặc thử',{exact:true})).toHaveValue('');
});
