import {test,expect,type Page} from '@playwright/test';
import {URLS} from '../helpers/session';
test.skip(process.env.E2E_SHOPPING_FIXTURE!=='1','Uses catalog fixture and mocked writes.');
async function choose(page:Page,slot:string,slug:string){await page.getByRole('group',{name:'Vị trí trong outfit'}).getByRole('button',{name:slot,exact:true}).click();await page.locator('.outfit-product-grid>button').filter({hasText:'XIII '+slug}).click();await page.getByRole('button',{name:'Chọn cho outfit',exact:true}).click();}
test('game layers inner top and jacket independently, saves model and all five SKUs',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(URLS.buyer+'/outfit');
 await choose(page,'Áo','tee-black');await choose(page,'Áo khoác','jacket-navy');await choose(page,'Quần','cargo-black');await choose(page,'Giày','sneaker');await choose(page,'Phụ kiện','bag');
 await expect(page.locator('.avatar-garment[data-selected=true]')).toHaveCount(5);await expect(page.locator('[data-garment="4"]')).toHaveAttribute('data-variant','qa-product-8-M');
 await page.getByRole('button',{name:/Tuỳ chỉnh nhân vật/}).click();await page.getByRole('button',{name:'Nữ',exact:true}).click();await page.getByRole('button',{name:'Tóc bob',exact:true}).click();await page.getByRole('button',{name:'Góc cạnh',exact:true}).click();
 await page.getByLabel('Đặt tên bộ phối',{exact:true}).fill('Layered look');await page.getByRole('button',{name:'Lưu bộ phối',exact:true}).click();await page.getByRole('button',{name:'Gỡ áo khoác',exact:true}).click();await expect(page.locator('[data-garment="0"]')).toHaveAttribute('data-variant','qa-product-0-M');
 await page.getByRole('button',{name:'Layered look ↗',exact:true}).click();await expect(page.locator('.avatar-garment[data-selected=true]')).toHaveCount(5);await page.reload();await expect(page.locator('.game-avatar')).toHaveAttribute('data-hair','bob');await expect(page.locator('.game-avatar')).toHaveAttribute('data-face','defined');await expect(page.locator('.avatar-garment[data-selected=true]')).toHaveCount(5);
 await page.screenshot({path:'docs/qa/v16/dress-up-desktop.png',fullPage:true});
 for(const width of [390,320]){await page.setViewportSize({width,height:844});await page.locator('.outfit-catalog').scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await expect(page.locator('.game-avatar')).toBeInViewport({ratio:.99});await choose(page,'Áo','hoodie-gray');await expect(page.locator('[data-garment="4"]')).toHaveAttribute('data-variant','qa-product-8-M');await page.screenshot({path:'docs/qa/v16/dress-up-mobile-'+width+'.png',fullPage:false});}
 expect(errors).toEqual([]);
});
test('old four-slot jacket draft migrates to outer layer without losing its SKU',async({page})=>{
 await page.addInitScript(()=>{if(!localStorage.getItem('xiii-outfit-v2:guest'))localStorage.setItem('xiii-outfit-v2:guest',JSON.stringify([{slug:'jacket-navy',variantId:'qa-product-8-M'},null,null,null]));});await page.goto(URLS.buyer+'/outfit');await expect(page.locator('[data-garment="4"]')).toHaveAttribute('data-variant','qa-product-8-M');await choose(page,'Áo','tee-black');await page.reload();await expect(page.locator('[data-garment="4"]')).toHaveAttribute('data-variant','qa-product-8-M');await expect(page.locator('[data-garment="0"]')).toHaveAttribute('data-variant','qa-product-0-M');
});
test('SKU artwork changes with variant and falls back when artwork is missing',async({page})=>{
 await page.route('**/products/bag',route=>route.fulfill({json:{success:true,data:{_id:'qa-product-5',slug:'bag',name:'XIII bag',attributes:{outfitPreview:{variantOverlays:{'qa-product-5-M':{neutral:'/products/bag.svg'},'qa-product-5-White-M':{feminine:'/products/tee-black.svg'}}}}}}}));
 await page.goto(URLS.buyer+'/outfit');await choose(page,'Phụ kiện','bag');await expect(page.locator('[data-garment="3"] image')).toHaveAttribute('href','/products/bag.svg');await page.getByRole('button',{name:'Đổi lựa chọn phụ kiện',exact:true}).click();await page.locator('.preview-choice select').selectOption('qa-product-5-White-M');await page.getByRole('button',{name:'Chọn cho outfit',exact:true}).click();await expect(page.locator('[data-garment="3"] image')).toHaveCount(0);await expect(page.locator('[data-garment="3"] rect')).toHaveAttribute('fill','#eee9df');await page.getByRole('button',{name:/Tuỳ chỉnh nhân vật/}).click();await page.getByRole('button',{name:'Nữ',exact:true}).click();await expect(page.locator('[data-garment="3"] image')).toHaveAttribute('href','/products/tee-black.svg');
});
test('seller binds artwork to each saved SKU and form, retains unrelated product attributes',async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('xiii_seller_access','fixture'));let payload:any;
 await page.route('**/seller/products/qa-product-0',async route=>{if(route.request().method()!=='PATCH')return route.continue();payload=route.request().postDataJSON();return route.fulfill({json:{success:true,data:{...payload,_id:'qa-product-0',status:'DRAFT'}}});});
 await page.goto(URLS.seller+'/products/qa-product-0');await page.getByLabel('URL artwork mặc thử',{exact:true}).fill('/products/tee-black.svg');await page.getByLabel('Dáng mẫu artwork',{exact:true}).selectOption('feminine');await page.getByLabel('URL artwork mặc thử',{exact:true}).fill('/products/hoodie-gray.svg');await page.getByLabel('SKU mặc thử',{exact:true}).selectOption('qa-product-0-L');await expect(page.getByLabel('URL artwork mặc thử',{exact:true})).toHaveValue('');await page.getByLabel('URL artwork mặc thử',{exact:true}).fill('javascript:bad');await page.getByRole('button',{name:'Lưu thông tin',exact:true}).click();await expect(page.locator('.seller-alert')).toContainText('URL artwork');expect(payload).toBeUndefined();await page.getByLabel('URL artwork mặc thử',{exact:true}).fill('');await page.getByRole('button',{name:'Lưu thông tin',exact:true}).click();await expect(page.locator('.seller-success')).toContainText('Đã lưu');expect(payload.attributes.fit).toBe('Oversized');expect(payload.attributes.outfitPreview.variantOverlays['qa-product-0-M']).toEqual({neutral:'/products/tee-black.svg',feminine:'/products/hoodie-gray.svg'});
});
test('catalog load more reaches products outside the first page',async({page})=>{
 await page.route('**/products?**',route=>route.fulfill({json:{success:true,data:[{_id:'later',slug:'jacket-navy',name:'XIII jacket-navy',primaryVariant:{price:100000}}],meta:{totalPages:2}}}));
 await page.goto(URLS.buyer+'/outfit');await page.getByLabel('Tìm món để phối',{exact:true}).fill('jacket');await page.getByRole('button',{name:'Tìm sản phẩm',exact:true}).click();await page.getByRole('button',{name:'Áo khoác',exact:true}).click();await page.getByRole('button',{name:'Xem thêm sản phẩm',exact:true}).click();await expect(page.getByRole('button',{name:'Xem thêm sản phẩm',exact:true})).toHaveCount(0);await expect(page.locator('.outfit-product-grid>button')).toHaveCount(1);
});
test('artwork upload rejects wrong canvas and locks SKU destination until valid upload finishes',async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('xiii_seller_access','fixture'));let writes=0;let release!:()=>void;const gate=new Promise<void>(r=>release=r);
 await page.route('**/uploads/presign',route=>{writes++;return route.fulfill({json:{success:true,data:{method:'POST',uploadUrl:URLS.seller+'/artwork-storage',fields:{key:'artwork'},publicUrl:'https://cdn.example.com/sku-artwork.png'}}});});await page.route('**/artwork-storage',async route=>{await gate;await route.fulfill({status:204});});await page.goto(URLS.seller+'/products/qa-product-0');
 const panel=page.locator('.outfit-artwork-editor');const input=panel.locator('input[type=file]');const create=async(width:number,height:number)=>Buffer.from(await page.evaluate(([w,h])=>{const c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d')!;x.fillStyle='#253346';x.fillRect(w*.4,h*.3,w*.2,h*.2);return c.toDataURL('image/png').split(',')[1];},[width,height]),'base64');
 await input.setInputFiles({name:'wrong.png',mimeType:'image/png',buffer:await create(100,100)});await panel.getByRole('button',{name:'Tải 1 ảnh lên',exact:true}).click();await expect(panel.getByRole('alert')).toContainText('360 × 620');expect(writes).toBe(0);await panel.getByRole('button',{name:'Bỏ ảnh đã chọn',exact:true}).click();
 await input.setInputFiles({name:'correct.png',mimeType:'image/png',buffer:await create(360,620)});await panel.getByRole('button',{name:'Tải 1 ảnh lên',exact:true}).click();await expect.poll(()=>writes).toBe(1);await expect(panel.getByLabel('SKU mặc thử',{exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Lưu thông tin',exact:true})).toBeDisabled();release();await expect(panel.getByLabel('URL artwork mặc thử',{exact:true})).toHaveValue('https://cdn.example.com/sku-artwork.png');await expect(panel.getByLabel('SKU mặc thử',{exact:true})).toBeEnabled();
});
