import {test,expect,type Page} from '@playwright/test';
import {readFileSync,mkdirSync} from 'node:fs';
mkdirSync('docs/qa/media-v9',{recursive:true});
import {URLS} from '../helpers/session';
test.skip(process.env.E2E_SHOPPING_FIXTURE!=='1','Local fixture and mocked uploads only.');
const wide=readFileSync('e2e/fixtures/images/editor-wide.png');
const picture={name:'wide.png',mimeType:'image/png',buffer:wide};
const group=(page:Page,label:string)=>page.getByRole('group',{name:label,exact:true});
async function mock(page:Page,role:'seller'|'admin'|'buyer'){
 await page.addInitScript(role=>localStorage.setItem(role==='buyer'?'xiii_access':'xiii_'+role+'_access','qa-session'),role);
 const metadata:any[]=[],bodies:Buffer[]=[];
 await page.route('**/uploads/presign',route=>{const body=route.request().postDataJSON();metadata.push(body);return route.fulfill({json:{success:true,data:{method:'POST',uploadUrl:URLS[role]+'/mock-image-storage',fields:{'Content-Type':body.contentType,key:'qa'},publicUrl:'https://cdn.example.com/'+metadata.length+'/'+body.fileName}}});});
 await page.route('**/mock-image-storage',route=>{bodies.push(route.request().postDataBuffer()!);return route.fulfill({status:204});});
 return {metadata,bodies};
}
function pngFromMultipart(body:Buffer){const start=body.indexOf(Buffer.from([137,80,78,71,13,10,26,10]));const end=body.indexOf(Buffer.from([0,0,0,0,73,69,78,68,174,66,96,130]),start);expect(start).toBeGreaterThan(-1);expect(end).toBeGreaterThan(start);return body.subarray(start,end+12)}
async function choose(page:Page,label:string){const g=group(page,label);await g.getByLabel(label,{exact:true}).setInputFiles(picture);await expect(g.getByRole('button',{name:'Tải 1 ảnh lên',exact:true})).toBeEnabled();return g}
test('crop and rotation export the preview geometry and preserve transparent pixels',async({page})=>{
 const m=await mock(page,'seller');await page.goto(URLS.seller+'/products/qa-product-0');await page.getByText('Chỉnh ảnh trước khi tải',{exact:true}).click();
 const g=await choose(page,'Chọn ảnh sản phẩm để chỉnh');expect(m.metadata).toHaveLength(0);await expect(page.getByRole('button',{name:'Lưu thông tin',exact:true})).toBeDisabled();
 await g.getByRole('button',{name:'Xoay 90°'}).click();await g.getByLabel('Tỷ lệ cắt').selectOption('1');
 await expect.poll(()=>g.locator('canvas').evaluate((c:HTMLCanvasElement)=>[c.width,c.height])).toEqual([80,80]);
 await g.screenshot({path:'docs/qa/media-v9/desktop-editor.png'});await g.getByRole('button',{name:'Tải 1 ảnh lên',exact:true}).click();await expect.poll(()=>m.bodies.length).toBe(1);
 const png=pngFromMultipart(m.bodies[0]);expect([png.readUInt32BE(16),png.readUInt32BE(20)]).toEqual([80,80]);
 const pixels=await page.evaluate(async base64=>{const img=new Image();img.src='data:image/png;base64,'+base64;await img.decode();const c=document.createElement('canvas');c.width=img.width;c.height=img.height;const ctx=c.getContext('2d')!;ctx.drawImage(img,0,0);return [[10,10],[70,10],[10,70],[70,70]].map(([x,y])=>Array.from(ctx.getImageData(x,y,1,1).data))},png.toString('base64'));
 expect(pixels).toEqual([[0,0,255,255],[255,0,0,255],[0,0,0,0],[0,255,0,255]]);expect(m.metadata[0].fileName).toBe('wide-edited.png');await expect(page.getByRole('button',{name:'Lưu thông tin',exact:true})).toBeEnabled();
});
test('crop settings persist per file and the original upload remains byte-identical',async({page})=>{
 const m=await mock(page,'seller');await page.goto(URLS.seller+'/products/qa-product-0');await page.getByText('Chỉnh ảnh trước khi tải',{exact:true}).click();const g=group(page,'Chọn ảnh sản phẩm để chỉnh');
 await g.getByLabel('Chọn ảnh sản phẩm để chỉnh').setInputFiles([picture,{...picture,name:'second.png'}]);await expect(g.getByRole('button',{name:'Tải 2 ảnh lên'})).toBeEnabled();
 await g.getByLabel('Tỷ lệ cắt').selectOption('1');await g.getByRole('button',{name:'2. second.png',exact:true}).click();await g.getByRole('button',{name:'1. wide.png',exact:true}).click();await expect(g.getByLabel('Tỷ lệ cắt')).toHaveValue('1');
 await g.getByRole('button',{name:'Tải 2 ảnh lên'}).click();await expect.poll(()=>m.bodies.length).toBe(2);expect(pngFromMultipart(m.bodies[0]).readUInt32BE(16)).toBe(80);expect(pngFromMultipart(m.bodies[1])).toEqual(wide);
});
test('product image drag, accessible ordering and deletion save exactly the visible order',async({page})=>{
 await mock(page,'seller');let saved:any;await page.route('**/seller/products/qa-product-0',async route=>{if(route.request().method()==='PATCH'){saved=route.request().postDataJSON();await route.fulfill({json:{success:true,data:{...saved,_id:'qa-product-0',status:'DRAFT'}}})}else await route.continue()});
 await page.goto(URLS.seller+'/products/qa-product-0');const urls=page.getByLabel('URL ảnh — mỗi dòng một ảnh');await urls.fill('https://cdn.example.com/a.png\nhttps://cdn.example.com/b.png\nhttps://cdn.example.com/c.png');
 await page.getByRole('button',{name:'Đưa ảnh 3 lên trước',exact:true}).click();await expect(urls).toHaveValue('https://cdn.example.com/a.png\nhttps://cdn.example.com/c.png\nhttps://cdn.example.com/b.png');
 const cards=page.locator('.image-order-card');await cards.nth(2).dragTo(cards.nth(0));await expect(urls).toHaveValue('https://cdn.example.com/b.png\nhttps://cdn.example.com/a.png\nhttps://cdn.example.com/c.png');
 await page.getByRole('button',{name:'Xóa ảnh 2',exact:true}).click();await page.getByRole('button',{name:'Lưu thông tin',exact:true}).click();await expect.poll(()=>saved?.images).toEqual(['https://cdn.example.com/b.png','https://cdn.example.com/c.png']);
});
test('shop logo and banner upload into editable URL fields and the shop save payload',async({page})=>{
 const m=await mock(page,'seller');let saved:any;await page.route('**/seller/shop',async route=>{if(route.request().method()==='PATCH')saved=route.request().postDataJSON();await route.fulfill({json:{success:true,data:{_id:'qa-shop',name:'XIII QA',slug:'xiii',status:'ACTIVE',accessRole:'OWNER',verified:true,permissions:['SHOP_SETTINGS'],...saved}}})});
 await page.goto(URLS.seller+'/settings');const g=await choose(page,'Upload logo shop');await expect(page.getByRole('button',{name:'Lưu thay đổi'})).toBeDisabled();await g.getByRole('button',{name:'Tải 1 ảnh lên'}).click();await expect(page.getByLabel('Logo URL',{exact:true})).toHaveValue(/1\/wide.png/);
 const banner=await choose(page,'Upload banner shop');await banner.getByRole('button',{name:'Tải 1 ảnh lên'}).click();await expect(page.getByLabel('Banner URL',{exact:true})).toHaveValue(/2\/wide.png/);await page.getByRole('button',{name:'Lưu thay đổi'}).click();await expect.poll(()=>saved?.logo).toBe('https://cdn.example.com/1/wide.png');expect(saved.banner).toBe('https://cdn.example.com/2/wide.png');expect(m.metadata.map(x=>x.purpose)).toEqual(['SHOP_LOGO','SHOP_BANNER']);
});
test('SKU image upload saves to its own SKU without appending product gallery images',async({page})=>{
 const m=await mock(page,'seller');let saved:any;await page.route('**/seller/variants/**',route=>{saved=route.request().postDataJSON();return route.fulfill({json:{success:true,data:{}}})});await page.goto(URLS.seller+'/products/qa-product-0');const original=await page.getByLabel('URL ảnh — mỗi dòng một ảnh').inputValue();const g=await choose(page,'Upload ảnh SKU 1');await expect(page.getByRole('button',{name:'Lưu SKU',exact:true}).first()).toBeDisabled();await g.getByRole('button',{name:'Tải 1 ảnh lên'}).click();await expect(page.locator('.seller-variant-editor').first().getByLabel('Ảnh riêng SKU')).toHaveValue(/wide.png/);await page.getByRole('button',{name:'Lưu SKU',exact:true}).first().click();await expect.poll(()=>saved?.image).toBe('https://cdn.example.com/1/wide.png');await expect(page.getByLabel('URL ảnh — mỗi dòng một ảnh')).toHaveValue(original);expect(m.metadata[0].purpose).toBe('PRODUCT_IMAGE');
});
test('review uploads attach media to the correct order item and enforce the six-image limit',async({page})=>{
 const m=await mock(page,'buyer');let saved:any;await page.route('**/reviews/mine?*',route=>route.fulfill({json:{success:true,data:{items:[{_id:'qa-item',productName:'QA shirt',order:{orderCode:'QA-1'}}],meta:{total:1,page:1,totalPages:1}}}}));await page.route('**/api/v1/reviews',route=>{saved=route.request().postDataJSON();return route.fulfill({json:{success:true,data:{}}})});
 await page.goto(URLS.buyer+'/account/reviews');await page.getByRole('button',{name:'Đánh giá',exact:true}).click();const g=group(page,'Upload ảnh đánh giá');
 await g.getByLabel('Upload ảnh đánh giá').setInputFiles(Array.from({length:7},(_,i)=>({...picture,name:i+'.png'})));await expect(g.getByRole('alert')).toContainText('tối đa 6');expect(m.metadata).toHaveLength(0);
 await g.getByLabel('Upload ảnh đánh giá').setInputFiles([picture,{...picture,name:'remove.png'}]);await expect(g.getByRole('button',{name:'Tải 2 ảnh lên'})).toBeEnabled();await expect(page.getByRole('button',{name:'Gửi đánh giá',exact:true})).toBeDisabled();await g.getByRole('button',{name:'Tải 2 ảnh lên'}).click();await expect(page.getByRole('button',{name:'Xóa ảnh đánh giá 2'})).toBeEnabled();await page.getByRole('button',{name:'Xóa ảnh đánh giá 2'}).click();await page.getByRole('button',{name:'Gửi đánh giá',exact:true}).click();await expect.poll(()=>saved?.media).toEqual(['https://cdn.example.com/1/wide.png']);expect(saved.orderItemId).toBe('qa-item');expect(m.metadata.every(x=>x.purpose==='REVIEW_IMAGE')).toBe(true);
});
test('return evidence upload keeps existing links and submits only the remaining attachments',async({page})=>{
 const m=await mock(page,'buyer');let saved:any;await page.route('**/returns/eligible/**',route=>route.fulfill({json:{success:true,data:{orderCode:'QA-1',subOrderCode:'QA-SUB',deadline:'2027-01-01',items:[{_id:'qa-item',productName:'QA shirt',quantity:1,returnableQuantity:1,unitPrice:100000}]}}}));await page.route('**/api/v1/returns',route=>{saved=route.request().postDataJSON();return route.fulfill({json:{success:true,data:{requestCode:'QA-RETURN'}}})});await page.route('**/account/returns/QA-RETURN',route=>route.fulfill({contentType:'text/html',body:'<p>QA return created</p>'}));
 await page.goto(URLS.buyer+'/account/returns/new?subOrderCode=QA-SUB');await page.getByLabel('Link ảnh/video bằng chứng (mỗi dòng 1 URL)').fill('https://cdn.example.com/existing.png');const g=await choose(page,'Upload ảnh bằng chứng trả hàng');await expect(page.getByRole('button',{name:'Gửi yêu cầu trả hàng'})).toBeDisabled();await g.getByRole('button',{name:'Tải 1 ảnh lên'}).click();await expect(page.getByRole('button',{name:'Xóa bằng chứng 2'})).toBeEnabled();await page.getByRole('button',{name:'Xóa bằng chứng 1'}).click();await page.getByRole('button',{name:'Gửi yêu cầu trả hàng'}).click();await expect.poll(()=>saved?.evidenceUrls).toEqual(['https://cdn.example.com/1/wide.png']);expect(saved.items).toEqual([{orderItemId:'qa-item',quantity:1}]);expect(m.metadata[0].purpose).toBe('RETURN_IMAGE');
});
test('mobile editor fits the viewport and discarding a pending selection unlocks saving',async({page})=>{
 await page.setViewportSize({width:375,height:812});await mock(page,'seller');await page.route('**/seller/shop',route=>route.fulfill({json:{success:true,data:{name:'QA',slug:'qa',status:'ACTIVE',accessRole:'OWNER',permissions:['SHOP_SETTINGS']}}}));await page.goto(URLS.seller+'/settings');const g=await choose(page,'Upload logo shop');await expect(page.getByRole('button',{name:'Lưu thay đổi'})).toBeDisabled();await g.getByRole('button',{name:'Xoay 90°'}).click();expect(await g.evaluate(el=>el.getBoundingClientRect().right<=innerWidth)).toBe(true);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await g.screenshot({path:'docs/qa/media-v9/mobile-editor.png'});await g.getByRole('button',{name:'Bỏ ảnh đã chọn'}).click();await expect(page.getByRole('button',{name:'Lưu thay đổi'})).toBeEnabled();
});
test('Admin edited mobile banner updates its own field and blocks switching destinations while pending',async({page})=>{
 const m=await mock(page,'admin');await page.goto(URLS.admin+'/cms');await page.getByText('Chỉnh ảnh banner điện thoại trước khi tải',{exact:true}).click();const g=await choose(page,'Chọn ảnh banner điện thoại để chỉnh');await expect(page.getByRole('button',{name:'Danh mục',exact:true})).toBeDisabled();await g.getByLabel('Tỷ lệ cắt').selectOption(String(9/16));await g.getByRole('button',{name:'Tải 1 ảnh lên'}).click();await expect(page.getByLabel('Mobile image URL',{exact:true})).toHaveValue(/wide-edited.png/);await expect(page.getByLabel('Image URL',{exact:true})).toHaveValue('');expect(m.metadata[0].purpose).toBe('CMS_BANNER');await expect(page.getByRole('button',{name:'Danh mục',exact:true})).toBeEnabled();
});
test('editor retries only failed files and preserves successful attachments',async({page})=>{
 const m=await mock(page,'seller');let attempts=0;await page.route('**/mock-image-storage',route=>{attempts++;if(attempts===2)return route.fulfill({status:503});m.bodies.push(route.request().postDataBuffer()!);return route.fulfill({status:204})});await page.goto(URLS.seller+'/products/qa-product-0');await page.getByText('Chỉnh ảnh trước khi tải',{exact:true}).click();const g=group(page,'Chọn ảnh sản phẩm để chỉnh');await g.getByLabel('Chọn ảnh sản phẩm để chỉnh').setInputFiles([picture,{...picture,name:'retry.png'}]);await g.getByRole('button',{name:'Tải 2 ảnh lên'}).click();await expect(g.getByRole('alert')).toContainText('503');await expect(g.getByRole('button',{name:'Tải 1 ảnh lên'})).toBeEnabled();await g.getByRole('button',{name:'Tải 1 ảnh lên'}).click();await expect(g.getByRole('alert')).toHaveCount(0);expect(m.metadata.map(x=>x.fileName)).toEqual(['wide.png','retry.png','retry.png']);await expect(page.getByLabel('URL ảnh — mỗi dòng một ảnh')).toHaveValue(/1\/wide.png\nhttps:\/\/cdn.example.com\/3\/retry.png/);
});
test('return upload rechecks remaining attachment slots if manual evidence links change after selection',async({page})=>{
 const m=await mock(page,'buyer');await page.route('**/returns/eligible/**',route=>route.fulfill({json:{success:true,data:{orderCode:'QA-1',subOrderCode:'QA-SUB',deadline:'2027-01-01',items:[{_id:'qa-item',productName:'QA shirt',quantity:1,returnableQuantity:1,unitPrice:100000}]}}}));await page.goto(URLS.buyer+'/account/returns/new?subOrderCode=QA-SUB');const g=await choose(page,'Upload ảnh bằng chứng trả hàng');await page.getByLabel('Link ảnh/video bằng chứng (mỗi dòng 1 URL)').fill(Array.from({length:8},(_,i)=>'https://cdn.example.com/'+i+'.png').join('\n'));await g.getByRole('button',{name:'Tải 1 ảnh lên'}).click();await expect(g.getByRole('alert')).toContainText('Chỉ còn chỗ cho 0 ảnh');expect(m.metadata).toHaveLength(0);await g.getByRole('button',{name:'Bỏ ảnh đã chọn'}).click();await expect(page.getByRole('button',{name:'Gửi yêu cầu trả hàng'})).toBeEnabled();
});
test('shop viewers cannot choose or upload logo and banner files',async({page})=>{
 const m=await mock(page,'seller');await page.route('**/seller/shop',route=>route.fulfill({json:{success:true,data:{name:'QA',slug:'qa',status:'ACTIVE',accessRole:'STAFF',permissions:[]}}}));await page.goto(URLS.seller+'/settings');await expect(group(page,'Upload logo shop').getByLabel('Upload logo shop')).toBeDisabled();await expect(group(page,'Upload banner shop').getByLabel('Upload banner shop')).toBeDisabled();await expect(page.getByRole('button',{name:'Lưu thay đổi'})).toBeDisabled();expect(m.metadata).toHaveLength(0);
});
