import {expect,test} from '@playwright/test';
import {URLS} from '../helpers/session';
test.skip(process.env.E2E_SHOPPING_FIXTURE!=='1','Local fixture with cart mocks only.');
test('logo depth follows mouse, resets with motion off and keeps home navigation',async({page})=>{
 await page.goto(URLS.buyer+'/');await expect(page.locator('html')).toHaveAttribute('data-motion','on');const logo=page.getByRole('link',{name:'XIII home'});let n=0;
 await expect.poll(async()=>{await logo.hover({position:{x:8+n++%2,y:8}});return logo.getAttribute('data-depth-active')}).toBe('true');await expect.poll(()=>logo.locator('.logo-face').evaluate(e=>getComputedStyle(e).transform)).not.toBe('none');
 await logo.screenshot({path:'docs/qa/threeui-v12/logo.png'});await page.getByRole('button',{name:'Tắt chuyển động',exact:true}).click();await expect(logo).not.toHaveAttribute('data-depth-active','true');expect(await logo.locator('.logo-face').evaluate(e=>getComputedStyle(e).transform)).toBe('none');await page.goto(URLS.buyer+'/product/bag');await page.getByRole('link',{name:'XIII home'}).click();await expect(page).toHaveURL(URLS.buyer+'/');
});
test('dimensional swatches select the actual color SKU and stay locked during cart writes',async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('xiii_access','qa-session'));let release!:()=>void;const gate=new Promise<void>(r=>release=r);let body:any;await page.route('**/cart/items',async route=>{body=route.request().postDataJSON();await gate;await route.fulfill({json:{success:true,data:{}}})});
 await page.goto(URLS.buyer+'/product/bag');await expect(page.locator('html')).toHaveAttribute('data-motion','on');const colors=page.locator('.detail-color-options:visible');await colors.getByRole('button',{name:'White',exact:true}).click();await expect(colors.getByRole('button',{name:'White',exact:true})).toHaveAttribute('aria-pressed','true');await expect(page.locator('.gallery-open img')).toHaveAttribute('src','/products/fallback.svg');
 expect(await colors.locator('.swatch-white').evaluate(e=>getComputedStyle(e).borderRadius)).toBe('50%');expect(await colors.locator('.swatch-white').evaluate(e=>getComputedStyle(e).transform)).not.toBe('none');await colors.screenshot({path:'docs/qa/threeui-v12/swatches.png'});
 await page.getByRole('button',{name:'Thêm vào giỏ',exact:true}).click();await expect(colors.getByRole('button',{name:'Black',exact:true})).toBeDisabled();release();await expect(colors.getByRole('button',{name:'Black',exact:true})).toBeEnabled();expect(body).toEqual({variantId:'qa-product-5-White-M',quantity:1});
});
test('cart loading pauses offscreen and in hidden tab, then resolves to an accessible empty state',async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('xiii_access','qa-session'));let release!:()=>void;const gate=new Promise<void>(r=>release=r);await page.route('**/cart',async route=>{if(route.request().resourceType()==='document'){await route.continue();return;}await gate;await route.fulfill({json:{success:true,data:{shops:[],summary:{itemCount:0,subtotal:0,canCheckout:false}}}})});
 await page.goto(URLS.buyer+'/cart');const statue=page.locator('.cart-state .state-sculpture');await expect(page.getByRole('status')).toContainText('Đang tải giỏ');await expect(statue).toHaveAttribute('data-animated','true');await page.addStyleTag({content:'.cart-shell{min-height:2200px}'});await page.evaluate(()=>scrollTo(0,1800));await expect(statue).toHaveAttribute('data-animated','false');await page.evaluate(()=>scrollTo(0,0));await expect(statue).toHaveAttribute('data-animated','true');
 await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'))});await expect(statue).toHaveAttribute('data-animated','false');await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:false});document.dispatchEvent(new Event('visibilitychange'))});await expect(statue).toHaveAttribute('data-animated','true');release();await expect(page.getByRole('heading',{name:'Giỏ hàng đang trống'})).toBeVisible();await expect(statue).toHaveAttribute('data-kind','empty');await expect(statue).toHaveAttribute('aria-hidden','true');await expect(statue).toHaveAttribute('data-animated','false');await expect(page.getByRole('link',{name:'Tiếp tục mua sắm'})).toHaveAttribute('href','/search');await page.locator('.cart-state').screenshot({path:'docs/qa/threeui-v12/empty-cart.png'});
});
test('reduced motion keeps state geometry static and mobile controls fit',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'});await page.setViewportSize({width:320,height:740});await page.goto(URLS.buyer+'/cart');await expect(page.getByRole('heading',{name:'Đăng nhập để xem giỏ hàng'})).toBeVisible();expect(await page.locator('.cart-state .state-bag').evaluate(e=>getComputedStyle(e).animationName)).toBe('none');await page.locator('.cart-state').screenshot({path:'docs/qa/threeui-v12/guest-mobile.png'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.goto(URLS.buyer+'/product/bag');await expect(page.locator('html')).toHaveAttribute('data-motion','off');await page.locator('.detail-color-options:visible').getByRole('button',{name:'White',exact:true}).click();expect(await page.locator('.detail-color-options:visible .swatch-white').evaluate(e=>getComputedStyle(e).transform)).toBe('none');
});
test('logged-in cart flight ends at cart, never message or notification links',async({page})=>{
 await page.addInitScript(()=>{localStorage.setItem('xiii_access','qa-session');const original=Element.prototype.animate;Element.prototype.animate=function(...args:Parameters<Element['animate']>){if(this.classList.contains('cart-flight')){const node=this as HTMLElement,frame=(args[0] as Keyframe[]).at(-1)!,match=String(frame.transform).match(/translate3d\(([-\d.]+)px,([-\d.]+)px/)!;(window as any).flightEnd={x:parseFloat(node.style.left)+parseFloat(node.style.width)/2+Number(match[1]),y:parseFloat(node.style.top)+parseFloat(node.style.height)/2+Number(match[2])}}return original.apply(this,args)}});
 await page.route('**/cart/items',route=>route.fulfill({json:{success:true,data:{}}}));await page.goto(URLS.buyer+'/product/tee-black');await expect(page.getByRole('link',{name:'Tin nhắn',exact:true})).toBeVisible();await page.getByRole('button',{name:'Thêm vào giỏ',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).flightEnd)).toBeTruthy();const end=await page.evaluate(()=>(window as any).flightEnd);const cart=(await page.getByRole('link',{name:'Giỏ hàng',exact:true}).boundingBox())!;expect(end.x).toBeCloseTo(cart.x+cart.width/2,1);expect(end.y).toBeCloseTo(cart.y+cart.height/2,1);
});
