import {expect,test,Page} from '@playwright/test';
import {loginBuyer,URLS} from '../helpers/session';
const API='http://localhost:4000/api/v1';
async function cartWithItem(page:Page){await loginBuyer(page);const token=await page.evaluate(()=>localStorage.getItem('xiii_access'));await page.request.delete(API+'/cart',{headers:{Authorization:'Bearer '+token}});await page.goto(URLS.buyer+'/product/xiii-hoodie-gray');await page.getByRole('button',{name:'Mua ngay',exact:true}).click();await page.waitForURL('**/cart');await expect(page.locator('.cart-line')).toHaveCount(1);}
test('cart confirmation supports cancel and recovers from a failed deletion',async({page})=>{
 await cartWithItem(page);await page.getByRole('button',{name:'Xóa tất cả',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Dọn lại giỏ hàng?',exact:true});await expect(dialog).toBeVisible();if(process.env.XIII_PREVIEW_DIR)await page.screenshot({path:process.env.XIII_PREVIEW_DIR+'/cart-confirm-e2e.png',animations:'disabled'});await expect(dialog.getByRole('button',{name:'Giữ lại',exact:true})).toBeFocused();
 await page.keyboard.press('Escape');await expect(dialog).not.toBeVisible();await expect(page.locator('.cart-line')).toHaveCount(1);
 await page.route('**/api/v1/cart',route=>route.request().method()==='DELETE'?route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({success:false,message:'Thử lại việc xóa giỏ'})}):route.continue());
 await page.getByRole('button',{name:'Xóa tất cả',exact:true}).click();await dialog.getByRole('button',{name:'Xóa toàn bộ',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('Thử lại việc xóa giỏ');await expect(dialog.getByRole('button',{name:'Xóa toàn bộ',exact:true})).toBeEnabled();
 await page.unroute('**/api/v1/cart');await dialog.getByRole('button',{name:'Xóa toàn bộ',exact:true}).click();await expect(page.getByRole('heading',{name:'Giỏ hàng đang trống',exact:true})).toBeVisible();
});
test('successful clear stays empty even when later cart reads fail',async({page})=>{
 await cartWithItem(page);let deleted=false;
 await page.route('**/api/v1/cart',async route=>{if(route.request().method()==='DELETE'){const response=await route.fetch();deleted=true;await route.fulfill({response});}else if(deleted)await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({success:false,message:'cart reads offline'})});else await route.continue();});
 await page.getByRole('button',{name:'Xóa tất cả',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Xóa toàn bộ',exact:true}).click();await expect(page.getByRole('heading',{name:'Giỏ hàng đang trống',exact:true})).toBeVisible();await expect(page.locator('.cart-line')).toHaveCount(0);await expect(page.locator('.header-actions a[title="Giỏ hàng"]:visible .action-badge')).toHaveCount(0);
});
test('notification mutations handle failures and repeated clicks without unhandled errors',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await loginBuyer(page);await page.goto(URLS.buyer+'/account/notifications');await expect(page.locator('.notification-list > button.unread').first()).toBeVisible();if(process.env.XIII_PREVIEW_DIR)await page.screenshot({path:process.env.XIII_PREVIEW_DIR+'/notifications-desktop-e2e.png',fullPage:true,animations:'disabled'});
 let writes=0;await page.route('**/notifications/**',async route=>{if(route.request().method()==='PATCH'){writes++;await new Promise(resolve=>setTimeout(resolve,120));await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({success:false,message:'Chưa ghi nhận đã đọc'})});}else await route.continue();});
 await page.locator('.notification-list > button.unread').first().click();await expect(page.locator('.notification-page').getByRole('alert')).toContainText('Chưa ghi nhận đã đọc');await expect(page.locator('.notification-list > button.unread').first()).toBeEnabled();expect(page.url()).toContain('/account/notifications');
 const all=page.getByRole('button',{name:'Đánh dấu đã đọc tất cả',exact:true});await all.evaluate((button:HTMLButtonElement)=>{button.click();button.click();button.click();});await expect(all).toBeEnabled();expect(writes).toBe(2);
 await page.unroute('**/notifications/**');await all.click();await expect(page.locator('.notification-count')).toHaveText('0 thông báo chưa đọc');await expect(page.locator('.notification-list > button.unread')).toHaveCount(0);await expect(page.locator('.notification-page').getByRole('alert')).toHaveCount(0);expect(errors).toEqual([]);
});
test('notifications recover from a failed initial load on mobile',async({page})=>{
 await loginBuyer(page);await page.setViewportSize({width:390,height:844});await page.route('**/notifications?**',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({success:false,message:'Notifications offline'})}));await page.goto(URLS.buyer+'/account/notifications');await expect(page.getByText('Chưa tải được thông báo.',{exact:true})).toBeVisible();await page.unroute('**/notifications?**');await page.getByRole('button',{name:'Thử lại',exact:true}).click();await expect(page.locator('.notification-list > button').first()).toBeVisible();await expect(page.locator('.notification-page').getByRole('alert')).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);if(process.env.XIII_PREVIEW_DIR)await page.screenshot({path:process.env.XIII_PREVIEW_DIR+'/notifications-mobile-e2e.png',fullPage:true,animations:'disabled'});
});
test('rapid chat clicks create one request and failures allow retry',async({page})=>{
 await loginBuyer(page);await page.goto(URLS.buyer+'/product/xiii-hoodie-gray');let requests=0;await page.route('**/chat/conversations',async route=>{requests++;await new Promise(resolve=>setTimeout(resolve,150));await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({success:false,message:'Chat tạm ngắt kết nối'})});});
 const chat=page.getByRole('button',{name:'Chat với shop',exact:true});await chat.evaluate((button:HTMLButtonElement)=>{button.click();button.click();button.click();});await expect(page.getByRole('status')).toContainText('Chat tạm ngắt kết nối');await expect(chat).toBeEnabled();expect(requests).toBe(1);
});
test('shop links filter by shop identity and unknown shops return no products',async({page,request})=>{
 const response=await request.get(API+'/products/xiii-hoodie-gray');const product=(await response.json()).data;const shop=product.shop;
 const found=await request.get(API+'/products?shop='+shop._id+'&limit=100');expect(found.ok()).toBe(true);const rows=(await found.json()).data;expect(rows.length).toBeGreaterThan(0);expect(rows.every((row:{shop:{_id:string}})=>row.shop._id===shop._id)).toBe(true);
 const missing=await request.get(API+'/products?shop=does-not-exist');expect((await missing.json()).data).toEqual([]);
 await page.goto(URLS.buyer+'/product/xiii-hoodie-gray');await page.getByRole('link',{name:'Xem gian hàng',exact:true}).click();await expect(page).toHaveURL(url=>url.searchParams.get('shop')===shop._id);await expect(page.locator('.active-filter-row:visible')).toContainText('Gian hàng: '+shop.name);await expect(page.locator('.product-card').first()).toBeVisible();
});
