'use client';
import {BUYER_STORE_URL} from '../../../shared/app-links';
import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { adminApi, hasAdminSession } from '../lib/client-api';
import {ImageUploader} from '../../../shared/image-uploader';
import { uploadAdminImage, IMAGE_ACCEPT, IMAGE_FORMATS } from '../lib/upload';
import { AdminShell } from './admin-shell';

type Banner={_id:string;key:string;placement:'HERO'|'PROMO'|'EDITORIAL';title:string;subtitle?:string;eyebrow?:string;image:string;mobileImage?:string;href:string;ctaLabel:string;sortOrder:number;active:boolean;startAt?:string|null;endAt?:string|null;adminNote?:string};
type Section={_id:string;key:string;title:string;subtitle?:string;type:string;sortOrder:number;active:boolean;config?:Record<string,any>};
type Category={_id:string;parentId?:string;name:string;slug:string;image?:string;icon?:string;level:number;sortOrder:number;active:boolean};
type Brand={_id:string;name:string;slug:string;logo?:string;description?:string;verified:boolean;active:boolean};
type Tab='banners'|'sections'|'categories'|'brands';
const previewSrc=(s?:string)=>!s?'/fallback.svg':s.startsWith('/')?BUYER_STORE_URL+s:s;
const fmt=(s?:string|null)=>s?new Intl.DateTimeFormat('vi-VN',{dateStyle:'short',timeStyle:'short'}).format(new Date(s)):'Luôn bật';
const localInput=(s?:string|null)=>s?new Date(new Date(s).getTime()-new Date(s).getTimezoneOffset()*60000).toISOString().slice(0,16):'';
const blankBanner={key:'',placement:'PROMO' as const,title:'',subtitle:'',eyebrow:'',image:'',mobileImage:'',href:'/search',ctaLabel:'Khám phá',sortOrder:10,active:true,startAt:'',endAt:'',adminNote:''};

const bannerPayload=(b:any)=>({key:b.key,placement:b.placement,title:b.title,subtitle:b.subtitle||'',eyebrow:b.eyebrow||'',image:b.image,mobileImage:b.mobileImage||'',href:b.href||'/search',ctaLabel:b.ctaLabel||'Khám phá',sortOrder:Number(b.sortOrder||0),active:Boolean(b.active),startAt:b.startAt?new Date(b.startAt).toISOString():undefined,endAt:b.endAt?new Date(b.endAt).toISOString():undefined,adminNote:b.adminNote||''});
const sectionPayload=(s:Section,patch:Partial<Section>={})=>{const v={...s,...patch};return {key:v.key,title:v.title,subtitle:v.subtitle||'',type:v.type,sortOrder:Number(v.sortOrder||0),active:Boolean(v.active),config:v.config||{}}};


export function AdminCmsClient(){
  const [tab,setTab]=useState<Tab>('banners');const [banners,setBanners]=useState<Banner[]>([]);const [sections,setSections]=useState<Section[]>([]);const [categories,setCategories]=useState<Category[]>([]);const [brands,setBrands]=useState<Brand[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [notice,setNotice]=useState('');
  const [bannerForm,setBannerForm]=useState<any>(blankBanner);const [editingBanner,setEditingBanner]=useState<string|null>(null);const [uploading,setUploading]=useState('');const [pendingMedia,setPendingMedia]=useState<Record<string,boolean>>({});const hasPendingMedia=Object.values(pendingMedia).some(Boolean);
  const [catForm,setCatForm]=useState({name:'',parentId:'',image:'',icon:'',sortOrder:10,active:true});
  const [brandForm,setBrandForm]=useState({name:'',logo:'',description:'',verified:false,active:true});
  const load=useCallback(async()=>{if(!hasAdminSession()){location.href='/login?next=%2Fcms';return}setLoading(true);setError('');try{const [b,s,c,br]=await Promise.all([adminApi<Banner[]>('/admin/cms/banners'),adminApi<Section[]>('/admin/cms/sections'),adminApi<Category[]>('/admin/categories'),adminApi<Brand[]>('/admin/brands')]);setBanners(b);setSections(s);setCategories(c);setBrands(br);}catch(e){setError(e instanceof Error?e.message:'Không tải được CMS')}finally{setLoading(false)}},[]);
  useEffect(()=>{load()},[load]);
  const activeNow=useMemo(()=>{const n=Date.now();return banners.filter(b=>b.active&&(!b.startAt||new Date(b.startAt).getTime()<=n)&&(!b.endAt||new Date(b.endAt).getTime()>=n)).length},[banners]);
  const flash=(m:string)=>{setNotice(m);setTimeout(()=>setNotice(''),2200)};
  async function uploadFile(file:File|undefined,purpose:'CMS_BANNER'|'CATEGORY_IMAGE'|'BRAND_LOGO',apply:(url:string)=>void){if(!file||uploading)return;setUploading(purpose);setError('');setNotice('');try{apply(await uploadAdminImage(file,purpose));flash('Đã tải ảnh thành công')}catch(e){setError(e instanceof Error?e.message:'Không upload được ảnh')}finally{setUploading('')}}
  async function saveBanner(e:FormEvent){e.preventDefault();if(uploading||hasPendingMedia)return;setError('');try{const payload=bannerPayload(bannerForm);if(editingBanner)await adminApi('/admin/cms/banners/'+editingBanner,{method:'PATCH',body:JSON.stringify(payload)});else await adminApi('/admin/cms/banners',{method:'POST',body:JSON.stringify(payload)});setBannerForm(blankBanner);setEditingBanner(null);await load();flash(editingBanner?'Đã cập nhật banner':'Đã tạo banner')}catch(e){setError(e instanceof Error?e.message:'Không lưu được banner')}}
  function editBanner(b:Banner){if(uploading||hasPendingMedia)return;setEditingBanner(b._id);setBannerForm({key:b.key,placement:b.placement,title:b.title,subtitle:b.subtitle||'',eyebrow:b.eyebrow||'',image:b.image,mobileImage:b.mobileImage||'',href:b.href,ctaLabel:b.ctaLabel,sortOrder:b.sortOrder,active:b.active,startAt:localInput(b.startAt),endAt:localInput(b.endAt),adminNote:b.adminNote||''});window.scrollTo({top:0,behavior:'smooth'})}
  async function toggleBanner(b:Banner){await adminApi('/admin/cms/banners/'+b._id,{method:'PATCH',body:JSON.stringify(bannerPayload({...b,active:!b.active}))});await load()}
  async function archiveBanner(b:Banner){if(!confirm('Ẩn banner này khỏi Homepage?'))return;await adminApi('/admin/cms/banners/'+b._id,{method:'DELETE'});await load();flash('Đã ẩn banner')}
  async function patchSection(s:Section,patch:Partial<Section>){await adminApi('/admin/cms/sections/'+s._id,{method:'PATCH',body:JSON.stringify(sectionPayload(s,patch))});await load()}
  async function moveSection(index:number,dir:-1|1){const sorted=[...sections].sort((a,b)=>a.sortOrder-b.sortOrder);const other=sorted[index+dir];const current=sorted[index];if(!other)return;const a=current.sortOrder,b=other.sortOrder;await Promise.all([patchRawSection(current,{sortOrder:b}),patchRawSection(other,{sortOrder:a})]);await load()}
  async function patchRawSection(s:Section,patch:Partial<Section>){return adminApi('/admin/cms/sections/'+s._id,{method:'PATCH',body:JSON.stringify(sectionPayload(s,patch))})}
  async function createCategory(e:FormEvent){e.preventDefault();if(uploading||hasPendingMedia)return;await adminApi('/admin/categories',{method:'POST',body:JSON.stringify({...catForm,parentId:catForm.parentId||undefined,sortOrder:Number(catForm.sortOrder)})});setCatForm({name:'',parentId:'',image:'',icon:'',sortOrder:10,active:true});await load();flash('Đã tạo danh mục')}
  async function toggleCategory(c:Category){await adminApi('/admin/categories/'+c._id,{method:'PATCH',body:JSON.stringify({name:c.name,parentId:c.parentId||undefined,image:c.image||'',icon:c.icon||'',sortOrder:c.sortOrder,active:!c.active})});await load()}
  async function createBrand(e:FormEvent){e.preventDefault();if(uploading||hasPendingMedia)return;await adminApi('/admin/brands',{method:'POST',body:JSON.stringify(brandForm)});setBrandForm({name:'',logo:'',description:'',verified:false,active:true});await load();flash('Đã tạo thương hiệu')}
  async function toggleBrand(b:Brand){await adminApi('/admin/brands/'+b._id,{method:'PATCH',body:JSON.stringify({name:b.name,logo:b.logo||'',description:b.description||'',verified:b.verified,active:!b.active})});await load()}

  const sortedSections=[...sections].sort((a,b)=>a.sortOrder-b.sortOrder);
  return <AdminShell active="cms">
    <section className="admin-page-head"><div><span>CONTENT MANAGEMENT</span><h1>CMS & Homepage</h1><p>Quản lý banner, thứ tự section, danh mục và thương hiệu mà không sửa source code.</p></div><a className="admin-primary" href={BUYER_STORE_URL} target="_blank">Mở Buyer Store ↗</a></section>
    <div className="admin-kpis"><article><small>Banner</small><strong>{banners.length}</strong><span>{activeNow} đang hiển thị theo lịch</span></article><article><small>Homepage sections</small><strong>{sections.filter(s=>s.active).length}/{sections.length}</strong><span>Section đang bật</span></article><article><small>Danh mục</small><strong>{categories.filter(c=>c.active).length}</strong><span>Đang public</span></article><article><small>Thương hiệu</small><strong>{brands.filter(b=>b.active).length}</strong><span>Đang public</span></article></div>
    {hasPendingMedia&&<p>Tải hoặc bỏ ảnh đã chọn trước khi lưu hoặc đổi tab.</p>}<div className="cms-tabs">{(['banners','sections','categories','brands'] as Tab[]).map(t=><button key={t} className={tab===t?'active':''} disabled={Boolean(uploading)||hasPendingMedia} onClick={()=>setTab(t)}>{t==='banners'?'Banner':t==='sections'?'Homepage sections':t==='categories'?'Danh mục':'Thương hiệu'}</button>)}</div>
    {notice&&<div className="admin-success">{notice}</div>}{error&&<div className="admin-alert">{error}</div>}{loading?<div className="admin-loading">Đang tải CMS…</div>:null}

    {!loading&&tab==='banners'&&<div className="cms-grid"><section className="admin-panel cms-form"><div className="admin-panel-head"><div><span>EDITOR</span><h2>{editingBanner?'Sửa banner':'Tạo banner'}</h2></div>{editingBanner&&<button className="cms-link" disabled={Boolean(uploading)||hasPendingMedia} onClick={()=>{setEditingBanner(null);setBannerForm(blankBanner)}}>Hủy sửa</button>}</div><form onSubmit={saveBanner}>
      <label>Key<input required value={bannerForm.key} onChange={e=>setBannerForm({...bannerForm,key:e.target.value})} placeholder="hero-october"/></label>
      <div className="cms-form-row"><label>Vị trí<select value={bannerForm.placement} onChange={e=>setBannerForm({...bannerForm,placement:e.target.value})}><option>HERO</option><option>PROMO</option><option>EDITORIAL</option></select></label><label>Thứ tự<input type="number" min="0" value={bannerForm.sortOrder} onChange={e=>setBannerForm({...bannerForm,sortOrder:e.target.value})}/></label></div>
      <label>Eyebrow<input value={bannerForm.eyebrow} onChange={e=>setBannerForm({...bannerForm,eyebrow:e.target.value})}/></label>
      <label>Tiêu đề<textarea required rows={2} value={bannerForm.title} onChange={e=>setBannerForm({...bannerForm,title:e.target.value})} placeholder={'STYLE\nYOUR OWN WAY'}/></label>
      <label>Phụ đề<input value={bannerForm.subtitle} onChange={e=>setBannerForm({...bannerForm,subtitle:e.target.value})}/></label>
      <label>Upload banner<input type="file" accept={IMAGE_ACCEPT} disabled={Boolean(uploading)} onChange={e=>{const file=e.currentTarget.files?.[0];e.currentTarget.value='';void uploadFile(file,'CMS_BANNER',url=>setBannerForm((v:any)=>({...v,image:url})));}}/></label><details className="image-upload-extra"><summary>Chỉnh ảnh banner trước khi tải</summary><ImageUploader label="Chọn ảnh banner để chỉnh" purpose="CMS_BANNER" disabled={Boolean(uploading)} upload={file=>uploadAdminImage(file,'CMS_BANNER')} onBusyChange={busy=>setUploading(busy?'CMS_BANNER':'')} onPendingChange={pending=>setPendingMedia(v=>({...v,image:pending}))} onUploaded={url=>setBannerForm((v:any)=>({...v,image:url}))}/></details><label>Image URL<input required value={bannerForm.image} onChange={e=>setBannerForm({...bannerForm,image:e.target.value})} placeholder="https://cdn.example.com/banner.webp"/></label>
      <label>Upload banner điện thoại<input type="file" accept={IMAGE_ACCEPT} disabled={Boolean(uploading)} onChange={e=>{const file=e.currentTarget.files?.[0];e.currentTarget.value='';void uploadFile(file,'CMS_BANNER',url=>setBannerForm((v:any)=>({...v,mobileImage:url})));}}/></label><details className="image-upload-extra"><summary>Chỉnh ảnh banner điện thoại trước khi tải</summary><ImageUploader label="Chọn ảnh banner điện thoại để chỉnh" purpose="CMS_BANNER" disabled={Boolean(uploading)} upload={file=>uploadAdminImage(file,'CMS_BANNER')} onBusyChange={busy=>setUploading(busy?'CMS_BANNER':'')} onPendingChange={pending=>setPendingMedia(v=>({...v,mobileImage:pending}))} onUploaded={url=>setBannerForm((v:any)=>({...v,mobileImage:url}))}/></details><p>{IMAGE_FORMATS} · Tối đa 12 MB/ảnh banner.</p><label>Mobile image URL<input value={bannerForm.mobileImage} onChange={e=>setBannerForm({...bannerForm,mobileImage:e.target.value})}/></label>
      <div className="cms-form-row"><label>Link<input value={bannerForm.href} onChange={e=>setBannerForm({...bannerForm,href:e.target.value})}/></label><label>CTA<input value={bannerForm.ctaLabel} onChange={e=>setBannerForm({...bannerForm,ctaLabel:e.target.value})}/></label></div>
      <div className="cms-form-row"><label>Bắt đầu<input type="datetime-local" value={bannerForm.startAt} onChange={e=>setBannerForm({...bannerForm,startAt:e.target.value})}/></label><label>Kết thúc<input type="datetime-local" value={bannerForm.endAt} onChange={e=>setBannerForm({...bannerForm,endAt:e.target.value})}/></label></div>
      <label className="cms-check"><input type="checkbox" checked={bannerForm.active} onChange={e=>setBannerForm({...bannerForm,active:e.target.checked})}/> Bật banner</label><button disabled={Boolean(uploading)||hasPendingMedia} className="admin-primary">{editingBanner?'Lưu thay đổi':'Tạo banner'}</button>
    </form></section><section className="admin-panel cms-list"><div className="admin-panel-head"><div><span>LIVE CONTENT</span><h2>Banner Homepage</h2></div><b>{banners.length} mục</b></div>{banners.map(b=><article key={b._id}><img src={previewSrc(b.image)} alt=""/><div><span>{b.placement} · #{b.sortOrder}</span><b>{b.title.replace(/\n/g,' / ')}</b><small>{b.eyebrow||b.key}</small><small>{fmt(b.startAt)} → {b.endAt?fmt(b.endAt):'không hết hạn'}</small></div><div className="cms-actions"><button onClick={()=>editBanner(b)}>Sửa</button><button onClick={()=>toggleBanner(b)}>{b.active?'Tắt':'Bật'}</button><button className="danger" onClick={()=>archiveBanner(b)}>Ẩn</button></div><i className={b.active?'on':'off'}>{b.active?'ACTIVE':'OFF'}</i></article>)}</section></div>}

    {!loading&&tab==='sections'&&<section className="admin-panel cms-section-list"><div className="admin-panel-head"><div><span>LAYOUT ORDER</span><h2>Thứ tự Homepage</h2></div><b>Kéo logic bằng ↑ ↓</b></div>{sortedSections.map((s,i)=><article key={s._id}><div className="cms-order"><button disabled={i===0} onClick={()=>moveSection(i,-1)}>↑</button><button disabled={i===sortedSections.length-1} onClick={()=>moveSection(i,1)}>↓</button></div><div><small>#{s.sortOrder} · {s.type}</small><b>{s.title}</b><span>{s.key}{s.subtitle?' · '+s.subtitle:''}</span></div><button className={s.active?'cms-toggle on':'cms-toggle'} onClick={()=>patchSection(s,{active:!s.active})}>{s.active?'Đang bật':'Đang tắt'}</button></article>)}</section>}

    {!loading&&tab==='categories'&&<div className="cms-grid"><section className="admin-panel cms-form"><div className="admin-panel-head"><div><span>CATALOG</span><h2>Tạo danh mục</h2></div></div><form onSubmit={createCategory}><label>Tên<input required value={catForm.name} onChange={e=>setCatForm({...catForm,name:e.target.value})}/></label><label>Danh mục cha<select value={catForm.parentId} onChange={e=>setCatForm({...catForm,parentId:e.target.value})}><option value="">Không có</option>{categories.filter(c=>c.level<2).map(c=><option key={c._id} value={c._id}>{'—'.repeat(c.level)} {c.name}</option>)}</select></label><label>Upload ảnh<input type="file" accept={IMAGE_ACCEPT} disabled={Boolean(uploading)} onChange={e=>{const file=e.currentTarget.files?.[0];e.currentTarget.value='';void uploadFile(file,'CATEGORY_IMAGE',url=>setCatForm(v=>({...v,image:url})));}}/></label><details className="image-upload-extra"><summary>Chỉnh ảnh trước khi tải</summary><ImageUploader label="Chọn ảnh để chỉnh" purpose="CATEGORY_IMAGE" disabled={Boolean(uploading)} upload={file=>uploadAdminImage(file,'CATEGORY_IMAGE')} onBusyChange={busy=>setUploading(busy?'CATEGORY_IMAGE':'')} onPendingChange={pending=>setPendingMedia(v=>({...v,category:pending}))} onUploaded={url=>setCatForm(v=>({...v,image:url}))}/></details><small>{IMAGE_FORMATS}. Tối đa 8 MB.</small><label>Ảnh URL<input value={catForm.image} onChange={e=>setCatForm({...catForm,image:e.target.value})} placeholder="https://cdn.example.com/category.webp"/></label><label>Thứ tự<input type="number" value={catForm.sortOrder} onChange={e=>setCatForm({...catForm,sortOrder:Number(e.target.value)})}/></label><button disabled={Boolean(uploading)||hasPendingMedia} className="admin-primary">Tạo danh mục</button></form></section><section className="admin-panel cms-simple-list"><div className="admin-panel-head"><div><span>ALL CATEGORIES</span><h2>Danh mục</h2></div></div>{categories.map(c=><article key={c._id}><span>{'—'.repeat(c.level)} {c.name}<small>/{c.slug} · #{c.sortOrder}</small></span><button className={c.active?'cms-toggle on':'cms-toggle'} onClick={()=>toggleCategory(c)}>{c.active?'Public':'Ẩn'}</button></article>)}</section></div>}

    {!loading&&tab==='brands'&&<div className="cms-grid"><section className="admin-panel cms-form"><div className="admin-panel-head"><div><span>BRANDS</span><h2>Tạo thương hiệu</h2></div></div><form onSubmit={createBrand}><label>Tên<input required value={brandForm.name} onChange={e=>setBrandForm({...brandForm,name:e.target.value})}/></label><label>Upload logo<input type="file" accept={IMAGE_ACCEPT} disabled={Boolean(uploading)} onChange={e=>{const file=e.currentTarget.files?.[0];e.currentTarget.value='';void uploadFile(file,'BRAND_LOGO',url=>setBrandForm(v=>({...v,logo:url})));}}/></label><details className="image-upload-extra"><summary>Chỉnh logo trước khi tải</summary><ImageUploader label="Chọn logo để chỉnh" purpose="BRAND_LOGO" disabled={Boolean(uploading)} upload={file=>uploadAdminImage(file,'BRAND_LOGO')} onBusyChange={busy=>setUploading(busy?'BRAND_LOGO':'')} onPendingChange={pending=>setPendingMedia(v=>({...v,brand:pending}))} onUploaded={url=>setBrandForm(v=>({...v,logo:url}))}/></details><small>{IMAGE_FORMATS}. Tối đa 5 MB.</small><label>Logo URL<input value={brandForm.logo} onChange={e=>setBrandForm({...brandForm,logo:e.target.value})}/></label><label>Mô tả<textarea rows={3} value={brandForm.description} onChange={e=>setBrandForm({...brandForm,description:e.target.value})}/></label><label className="cms-check"><input type="checkbox" checked={brandForm.verified} onChange={e=>setBrandForm({...brandForm,verified:e.target.checked})}/> Verified</label><button disabled={Boolean(uploading)||hasPendingMedia} className="admin-primary">Tạo thương hiệu</button></form></section><section className="admin-panel cms-simple-list"><div className="admin-panel-head"><div><span>ALL BRANDS</span><h2>Thương hiệu</h2></div></div>{brands.map(b=><article key={b._id}><span><b>{b.name} {b.verified?'✓':''}</b><small>/{b.slug}</small></span><button className={b.active?'cms-toggle on':'cms-toggle'} onClick={()=>toggleBrand(b)}>{b.active?'Public':'Ẩn'}</button></article>)}</section></div>}
  </AdminShell>
}
