'use client';
import { useCallback,useEffect,useState } from 'react';
import { adminApi,hasAdminSession } from '../lib/client-api';
import { AdminShell } from './admin-shell';
type Row={_id:string;email:string;fullName:string;roles:string[];status:string;lastLoginAt?:string;access:{permissions:string[];status:string}};type Data={items:Row[];availablePermissions:string[]};
export function AdminAccessClient(){const[data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const load=useCallback(async()=>{if(!hasAdminSession()){location.href='/login?next=%2Fadmins';return;}try{setData(await adminApi<Data>('/admin/access/admins'));setError('')}catch(e){setError(e instanceof Error?e.message:'Không tải được admin access')}},[]);useEffect(()=>{load()},[load]);
async function add(){const email=prompt('Email user đã đăng ký XIII:');if(!email||!data)return;const raw=prompt('Permissions, ngăn cách bằng dấu phẩy:',data.availablePermissions.slice(0,4).join(','));if(raw===null)return;const permissions=raw.split(',').map(x=>x.trim()).filter(Boolean);setBusy(true);try{await adminApi('/admin/access/admins',{method:'POST',body:JSON.stringify({email,permissions})});await load()}catch(e){setError(e instanceof Error?e.message:'Không tạo được Admin')}finally{setBusy(false)}}
async function edit(r:Row){if(r.roles.includes('SUPER_ADMIN'))return;const raw=prompt('Permissions, ngăn cách bằng dấu phẩy:',r.access.permissions.join(','));if(raw===null)return;const status=(prompt('Trạng thái ACTIVE hoặc SUSPENDED',r.access.status)||r.access.status).toUpperCase();const permissions=raw.split(',').map(x=>x.trim()).filter(Boolean);setBusy(true);try{await adminApi(`/admin/access/admins/${r._id}`,{method:'PATCH',body:JSON.stringify({permissions,status})});await load()}catch(e){setError(e instanceof Error?e.message:'Không cập nhật được Admin')}finally{setBusy(false)}}
return <AdminShell active="admins"><section className="admin-page-head"><div><span>RBAC / ADMIN ACCESS</span><h1>Admin roles & permissions</h1><p>SUPER_ADMIN bypass permission profile; ADMIN chỉ gọi được module đã cấp quyền.</p></div><button className="admin-primary" disabled={busy} onClick={add}>+ Cấp quyền Admin</button></section>{error&&<div className="admin-alert">{error}</div>}<section className="admin-panel admin-table-panel"><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Admin</th><th>Role</th><th>Access</th><th>Permissions</th><th>Last login</th><th></th></tr></thead><tbody>{data?.items.map(r=><tr key={r._id}><td><b>{r.fullName}</b><small className="admin-sub">{r.email}</small></td><td>{r.roles.join(', ')}</td><td><span className={'admin-status '+(r.access.status==='ACTIVE'?'active':'hidden')}>{r.access.status}</span></td><td><small>{r.roles.includes('SUPER_ADMIN')?'ALL / BYPASS':r.access.permissions.join(' · ')||'No permissions'}</small></td><td>{r.lastLoginAt?new Date(r.lastLoginAt).toLocaleString('vi-VN'):'—'}</td><td>{!r.roles.includes('SUPER_ADMIN')&&<button className="admin-secondary" disabled={busy} onClick={()=>edit(r)}>Phân quyền</button>}</td></tr>)}</tbody></table></div></section></AdminShell>}
