'use client';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { adminApi, hasAdminSession } from '../lib/client-api';
import { AdminShell } from './admin-shell';

type UserRow={_id:string;email:string;phone?:string;fullName:string;roles:string[];status:string;emailVerified:boolean;phoneVerified:boolean;lastLoginAt?:string;createdAt:string};
type Data={items:UserRow[];meta:{page:number;limit:number;total:number;totalPages:number}};
const dt=(s?:string)=>s?new Intl.DateTimeFormat('vi-VN',{dateStyle:'short',timeStyle:'short'}).format(new Date(s)):'—';
export function AdminUsersClient(){
  const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
  const [status,setStatus]=useState('ALL'),[role,setRole]=useState('ALL'),[query,setQuery]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(1);
  const load=useCallback(async()=>{if(!hasAdminSession()){location.href='/login?next=%2Fusers';return;}setLoading(true);setError('');try{const qs=new URLSearchParams({page:String(page),limit:'20'});if(status!=='ALL')qs.set('status',status);if(role!=='ALL')qs.set('role',role);if(search)qs.set('search',search);setData(await adminApi<Data>('/admin/users?'+qs));}catch(e){setError(e instanceof Error?e.message:'Không tải được users');}finally{setLoading(false)}},[status,role,search,page]);
  useEffect(()=>{load()},[load]);
  function submit(e:FormEvent){e.preventDefault();setPage(1);setSearch(query.trim())}
  return <AdminShell active="users"><section className="admin-page-head"><div><span>USER GOVERNANCE</span><h1>Người dùng</h1><p>Tìm kiếm, kiểm tra trạng thái tài khoản, xác minh liên hệ và khóa/mở tài khoản.</p></div><div className="admin-queue-chip"><b>{data?.meta.total??'—'}</b><span>tài khoản</span></div></section><section className="admin-panel admin-table-panel"><div className="admin-toolbar admin-users-toolbar"><div className="admin-filter-row"><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="ALL">Mọi trạng thái</option><option value="ACTIVE">ACTIVE</option><option value="BLOCKED">BLOCKED</option><option value="PENDING">PENDING</option></select><select value={role} onChange={e=>{setRole(e.target.value);setPage(1)}}><option value="ALL">Mọi role</option><option value="BUYER">BUYER</option><option value="SELLER">SELLER</option><option value="ADMIN">ADMIN</option><option value="SUPER_ADMIN">SUPER_ADMIN</option></select></div><form onSubmit={submit} className="admin-search"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tên / email / số điện thoại…"/><button>Tìm</button></form></div>{error&&<div className="admin-alert">{error}</div>}{loading?<div className="admin-loading">Đang tải người dùng…</div>:data?.items.length?<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Người dùng</th><th>Role</th><th>Xác minh</th><th>Trạng thái</th><th>Last login</th><th>Ngày tạo</th><th></th></tr></thead><tbody>{data.items.map(u=><tr key={u._id}><td><b>{u.fullName}</b><small className="admin-sub">{u.email}{u.phone?' · '+u.phone:''}</small></td><td><div className="admin-role-tags">{u.roles.map(r=><span key={r}>{r}</span>)}</div></td><td><small className={u.emailVerified?'verify-ok':'verify-no'}>Email {u.emailVerified?'✓':'—'}</small><small className={u.phoneVerified?'verify-ok':'verify-no'}>Phone {u.phoneVerified?'✓':'—'}</small></td><td><span className={'admin-status '+u.status.toLowerCase()}>{u.status}</span></td><td>{dt(u.lastLoginAt)}</td><td>{dt(u.createdAt)}</td><td><a className="admin-review-link" href={'/users/'+u._id}>Chi tiết →</a></td></tr>)}</tbody></table></div>:<div className="admin-empty"><h2>Không có user</h2><p>Thử thay đổi bộ lọc hoặc từ khóa.</p></div>}{data&&data.meta.totalPages>1&&<div className="admin-pagination"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>← Trước</button><span>Trang {page}/{data.meta.totalPages}</span><button disabled={page>=data.meta.totalPages} onClick={()=>setPage(p=>p+1)}>Sau →</button></div>}</section></AdminShell>
}
