'use client';
import { FormEvent,useCallback,useEffect,useState } from 'react';
import { adminApi,hasAdminSession } from '../lib/client-api';
import { AdminShell } from './admin-shell';
const money=(n:number)=>new Intl.NumberFormat('vi-VN').format(Math.round(n||0))+'₫'; const dt=(s?:string)=>s?new Intl.DateTimeFormat('vi-VN',{dateStyle:'short',timeStyle:'short'}).format(new Date(s)):'—';
type Row={_id:string;orderCode:string;status:string;paymentStatus:string;paymentMethod:string;totalAmount:number;createdAt:string;subOrderCount:number;buyer:{fullName:string;email:string;status:string}}; type Data={items:Row[];meta:{page:number;total:number;totalPages:number};statusCounts:Record<string,number>;paymentCounts:Record<string,number>};
export function AdminOrdersClient(){const [data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[status,setStatus]=useState('ALL'),[payment,setPayment]=useState('ALL'),[method,setMethod]=useState('ALL'),[query,setQuery]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(1);
 const load=useCallback(async()=>{if(!hasAdminSession()){location.href='/login?next=%2Forders';return;}setLoading(true);setError('');try{const q=new URLSearchParams({page:String(page),limit:'20'});if(status!=='ALL')q.set('status',status);if(payment!=='ALL')q.set('paymentStatus',payment);if(method!=='ALL')q.set('paymentMethod',method);if(search)q.set('search',search);setData(await adminApi<Data>('/admin/orders?'+q));}catch(e){setError(e instanceof Error?e.message:'Không tải được đơn hàng')}finally{setLoading(false)}},[status,payment,method,search,page]); useEffect(()=>{load()},[load]); function submit(e:FormEvent){e.preventDefault();setPage(1);setSearch(query.trim())}
 return <AdminShell active="orders"><section className="admin-page-head"><div><span>ORDER OPERATIONS</span><h1>Đơn hàng toàn sàn</h1><p>Theo dõi Master Order, payment state và các SubOrder theo shop.</p></div><div className="admin-queue-chip"><b>{data?.meta.total??'—'}</b><span>đơn</span></div></section><section className="admin-panel admin-table-panel"><div className="admin-toolbar admin-users-toolbar"><div className="admin-filter-row"><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="ALL">Mọi trạng thái</option>{['PENDING_PAYMENT','PAID','CONFIRMED','PACKING','READY_TO_SHIP','SHIPPED','DELIVERED','COMPLETED','CANCELLED','DISPUTED','REFUNDED'].map(x=><option key={x}>{x}</option>)}</select><select value={payment} onChange={e=>{setPayment(e.target.value);setPage(1)}}><option value="ALL">Mọi payment</option>{['PENDING','PROCESSING','SUCCESS','FAILED','CANCELLED','PARTIALLY_REFUNDED','REFUNDED'].map(x=><option key={x}>{x}</option>)}</select><select value={method} onChange={e=>{setMethod(e.target.value);setPage(1)}}><option value="ALL">Mọi phương thức</option><option>COD</option><option>MOMO</option><option>VNPAY</option></select></div><form className="admin-search" onSubmit={submit}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Mã đơn / voucher…"/><button>Tìm</button></form></div>{error&&<div className="admin-alert">{error}</div>}{loading?<div className="admin-loading">Đang tải đơn hàng…</div>:data?.items.length?<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Đơn</th><th>Buyer</th><th>Order status</th><th>Payment</th><th>Tổng</th><th>SubOrders</th><th>Ngày tạo</th><th></th></tr></thead><tbody>{data.items.map(o=><tr key={o._id}><td><b>{o.orderCode}</b><small className="admin-sub">{o.paymentMethod}</small></td><td><b>{o.buyer.fullName}</b><small className="admin-sub">{o.buyer.email}</small></td><td><span className={'admin-status '+o.status.toLowerCase()}>{o.status}</span></td><td><span className={'admin-status '+o.paymentStatus.toLowerCase()}>{o.paymentStatus}</span></td><td><b>{money(o.totalAmount)}</b></td><td>{o.subOrderCount}</td><td>{dt(o.createdAt)}</td><td><a className="admin-review-link" href={'/orders/'+o.orderCode}>Chi tiết →</a></td></tr>)}</tbody></table></div>:<div className="admin-empty"><h2>Không có đơn phù hợp</h2></div>}{data&&data.meta.totalPages>1&&<div className="admin-pagination"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>← Trước</button><span>Trang {page}/{data.meta.totalPages}</span><button disabled={page>=data.meta.totalPages} onClick={()=>setPage(p=>p+1)}>Sau →</button></div>}</section></AdminShell>}
