'use client';
import { useEffect, useState } from 'react';
import { adminApi, hasAdminSession } from '../lib/client-api';
import { AdminShell } from './admin-shell';
const money=(n:number)=>new Intl.NumberFormat('vi-VN').format(Math.round(n))+'₫';
type Summary={range:{from:string;to:string};kpis:{orders:number;gmv:number;platformRevenue:number;activeBuyers:number;activeSellers:number;activeShops:number;productViews:number};operations:{pendingProducts:number;openReturns:number;openDisputes:number;withdrawalQueue:number};inventory:{lowStockSkus:number;outOfStockSkus:number}};
export function AdminDashboardClient(){
  const [s,setS]=useState<Summary|null>(null);const [error,setError]=useState('');
  useEffect(()=>{if(!hasAdminSession()){location.href='/login';return;}adminApi<Summary>('/admin/analytics').then(setS).catch(e=>setError(e instanceof Error?e.message:'Không tải được dashboard'));},[]);
  return <AdminShell active="overview"><section className="admin-page-head"><div><span>MARKETPLACE OVERVIEW</span><h1>Vận hành XIII Marketplace</h1><p>Dashboard 30 ngày lấy trực tiếp từ Order, Finance, Product View, Return và Inventory.</p></div><a className="admin-primary" href="/analytics">Mở báo cáo đầy đủ →</a></section>{error&&<div className="admin-alert">{error}</div>}<div className="admin-kpis"><article><small>GMV 30 ngày</small><strong>{s?money(s.kpis.gmv):'—'}</strong><span>{s?.kpis.orders??'—'} đơn hợp lệ</span></article><article><small>Platform revenue</small><strong>{s?money(s.kpis.platformRevenue):'—'}</strong><span>Phí sàn snapshot từ SubOrder</span></article><article><small>Buyer hoạt động</small><strong>{s?.kpis.activeBuyers??'—'}</strong><span>{s?.kpis.activeSellers??'—'} seller · {s?.kpis.activeShops??'—'} shop</span></article><article><small>Product views</small><strong>{s?.kpis.productViews??'—'}</strong><span>Product detail views trong kỳ</span></article></div><div className="admin-analytics-main"><section className="admin-panel"><div className="admin-panel-head"><div><span>OPERATIONS QUEUE</span><h2>Việc cần xử lý</h2></div></div><div className="admin-op-grid"><a href="/products?status=PENDING_REVIEW"><small>Sản phẩm chờ duyệt</small><b>{s?.operations.pendingProducts??'—'}</b></a><a href="/after-sales"><small>Return đang mở</small><b>{s?.operations.openReturns??'—'}</b></a><a href="/after-sales"><small>Dispute mở</small><b>{s?.operations.openDisputes??'—'}</b></a><a href="/finance"><small>Withdrawal queue</small><b>{s?.operations.withdrawalQueue??'—'}</b></a></div></section><section className="admin-panel"><div className="admin-panel-head"><div><span>INVENTORY RISK</span><h2>Tình trạng kho toàn sàn</h2></div></div><div className="admin-op-grid"><a href="/analytics"><small>SKU sắp hết</small><b>{s?.inventory.lowStockSkus??'—'}</b></a><a href="/analytics"><small>SKU hết hàng</small><b>{s?.inventory.outOfStockSkus??'—'}</b></a></div></section></div></AdminShell>;
}
