export const SHOP_PERMISSIONS_KEY = 'shop_permissions';
export const ADMIN_PERMISSIONS_KEY = 'admin_permissions';

export const SHOP_PERMISSIONS = [
  'SHOP_VIEW','SHOP_SETTINGS','TEAM_MANAGE','PRODUCT_READ','PRODUCT_WRITE','INVENTORY_READ','INVENTORY_WRITE',
  'ORDER_READ','ORDER_FULFILL','PROMOTION_MANAGE','CHAT_REPLY','REVIEW_REPLY','RETURN_MANAGE','ANALYTICS_VIEW',
  'FINANCE_VIEW','FINANCE_WITHDRAW'
] as const;
export type ShopPermission = typeof SHOP_PERMISSIONS[number];

export const ADMIN_PERMISSIONS = [
  'DASHBOARD_VIEW','PRODUCTS_MODERATE','CMS_MANAGE','SELLERS_MANAGE','RETURNS_MANAGE','REVIEWS_MODERATE',
  'FINANCE_MANAGE','ANALYTICS_VIEW','USERS_MANAGE','ORDERS_MANAGE','PAYMENTS_MANAGE','SETTINGS_MANAGE','ADMIN_MANAGE','AUDIT_VIEW'
] as const;
export type AdminPermission = typeof ADMIN_PERMISSIONS[number];

export const SHOP_ROLE_DEFAULTS: Record<string, ShopPermission[]> = {
  OWNER: [...SHOP_PERMISSIONS],
  MANAGER: SHOP_PERMISSIONS.filter(p => !['FINANCE_WITHDRAW'].includes(p)),
  STAFF: ['SHOP_VIEW','PRODUCT_READ','INVENTORY_READ','ORDER_READ','ORDER_FULFILL','CHAT_REPLY','REVIEW_REPLY','RETURN_MANAGE'],
};
