'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { hasSellerSession, sellerApi } from '../lib/client-api';
import { SellerShell } from './seller-shell';
const money=(n:number)=>new Intl.NumberFormat('vi-VN').format(n)+'₫';
const date=(v?:string)=>v?new Intl.DateTimeFormat('vi-VN',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v)):'—';
const STATUS:Record<string,string>={PENDING_PAYMENT:'Chờ thanh toán',PAID:'Đã thanh toán',CONFIRMED:'Đã xác nhận',PACKING:'Đang đóng gói',READY_TO_SHIP:'Chờ lấy hàng',SHIPPED:'Đang giao',DELIVERED:'Đã giao',COMPLETED:'Hoàn tất',CANCELLED:'Đã hủy',RETURN_REQUESTED:'Yêu cầu trả hàng',RETURN_APPROVED:'Đã duyệt trả',RETURNED:'Đang trả về',REFUND_PENDING:'Chờ hoàn tiền',REFUNDED:'Đã hoàn tiền',DISPUTED:'Khiếu nại'};
const ACTION:Record<string,string>={CONFIRMED:'Xác nhận đơn',PACKING:'Bắt đầu đóng gói',READY_TO_SHIP:'Đóng gói xong',SHIPPED:'Bàn giao vận chuyển',DELIVERED:'Đánh dấu đã giao'};
type Detail={_id:string;subOrderCode:string;status:string;subtotal:number;shippingFee:number;platformFee:number;sellerRevenue:number;trackingCode?:string;shippingProvider?:string;nextStatus?:string;createdAt:string;order:{orderCode:string;status:string;paymentMethod:string;paymentStatus:string;shippingMethod:string;shippingAddress:Record<string,string>;createdAt:string};shop?:{name:string;verified:boolean};items:Array<{_id:string;productName:string;image:string;quantity:number;unitPrice:number;totalPrice:number;variantSnapshot:{sku?:string;attributes?:Record<string,string>}}>;timeline:Array<{_id:string;fromStatus?:string;toStatus:string;note:string;createdAt:string}>};
export function SellerOrderDetailClient({subOrderCode}:{subOrderCode:string}){
 const [data,setData]=useState<Detail|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const [tracking,setTracking]=useState(''),[provider,setProvider]=useState('GHN');
 const load=useCallback(async()=>{if(!hasSellerSession()){window.location.href='/login?next='+encodeURIComponent('/orders/'+subOrderCode);return;}try{const d=await sellerApi<Detail>('/seller/orders/'+encodeURIComponent(subOrderCode));setData(d);setTracking(d.trackingCode||'');setProvider(d.shippingProvider||'GHN');}catch(e){setError(e instanceof Error?e.message:'Không tải được đơn');}},[subOrderCode]);useEffect(()=>{load();},[load]);
 const total=useMemo(()=>data?data.subtotal+data.shippingFee:0,[data]);
 async function advance(){if(!data?.nextStatus)return;if(data.nextStatus==='SHIPPED'&&!tracking.trim()){setError('Nhập mã vận đơn trước khi bàn giao vận chuyển.');return;}if(!confirm(`${ACTION[data.nextStatus]||'Cập nhật'}: ${data.subOrderCode}?`))return;setBusy(true);setError('');try{await sellerApi('/seller/orders/'+encodeURIComponent(data.subOrderCode)+'/status',{method:'PATCH',body:JSON.stringify({status:data.nextStatus,trackingCode:tracking.trim()||undefined,shippingProvider:provider,note:`Seller action: ${ACTION[data.nextStatus]||data.nextStatus}`})});await load();}catch(e){setError(e instanceof Error?e.message:'Không cập nhật được đơn');}finally{setBusy(false)}}
 if(!data)return <SellerShell active="orders"><div className="seller-loading">{error||'Đang tải chi tiết đơn…'}</div></SellerShell>;
 const a=data.order.shippingAddress;
 return <SellerShell active="orders"><section className="seller-page-head seller-order-detail-head"><div><a href="/orders">← Danh sách đơn</a><span>SUBORDER DETAIL</span><h1>{data.subOrderCode}</h1><p>Master {data.order.orderCode} · {date(data.order.createdAt)}</p></div><div className="seller-detail-actions"><span className={'seller-badge status-'+data.status.toLowerCase()}>{STATUS[data.status]||data.status}</span>{data.nextStatus&&<button className="seller-primary" disabled={busy} onClick={advance}>{busy?'Đang cập nhật…':ACTION[data.nextStatus]||data.nextStatus}</button>}</div></section>
 {error&&<div className="seller-alert">{error}</div>}
 <div className="seller-detail-grid"><section className="seller-detail-main"><article className="seller-panel"><div className="seller-panel-head"><div><span>PRODUCTS</span><h2>Sản phẩm trong đơn</h2></div><b>{data.items.reduce((n,x)=>n+x.quantity,0)} món</b></div>{data.items.map(item=><div className="seller-detail-item" key={item._id}><img src={item.image||'/products/fallback.svg'} alt=""/><div><b>{item.productName}</b><small>{Object.values(item.variantSnapshot?.attributes||{}).filter(Boolean).join(' · ')}</small><span>SKU {item.variantSnapshot?.sku||'—'} · {money(item.unitPrice)} × {item.quantity}</span></div><strong>{money(item.totalPrice)}</strong></div>)}<div className="seller-detail-total"><span>Tạm tính <b>{money(data.subtotal)}</b></span><span>Phí ship <b>{money(data.shippingFee)}</b></span><span>Platform fee <b>−{money(data.platformFee)}</b></span><span>Seller revenue <strong>{money(data.sellerRevenue)}</strong></span></div></article>
 <article className="seller-panel"><div className="seller-panel-head"><div><span>TIMELINE</span><h2>Lịch sử xử lý</h2></div></div><div className="seller-timeline">{data.timeline.map((t,i)=><div key={t._id}><span>{i+1}</span><section><b>{STATUS[t.toStatus]||t.toStatus}</b><small>{date(t.createdAt)}</small><p>{t.note||'Cập nhật trạng thái'}</p></section></div>)}</div></article></section>
 <aside className="seller-detail-side"><section className="seller-panel"><span className="eyebrow">CUSTOMER</span><h2>Người nhận</h2><b>{a.recipientName} · {a.phone}</b><p>{a.addressLine}<br/>{a.ward}, {a.district}, {a.province}</p></section><section className="seller-panel"><span className="eyebrow">PAYMENT</span><h2>Thanh toán</h2><div className="seller-kv"><span>Phương thức</span><b>{data.order.paymentMethod}</b></div><div className="seller-kv"><span>Trạng thái</span><b>{data.order.paymentStatus}</b></div><div className="seller-kv"><span>Giao hàng</span><b>{data.order.shippingMethod}</b></div><div className="seller-kv"><span>Tổng khách trả</span><b>{money(total)}</b></div></section><section className="seller-panel"><span className="eyebrow">SHIPPING</span><h2>Vận chuyển</h2><label>Đơn vị vận chuyển<select value={provider} onChange={e=>setProvider(e.target.value)} disabled={!['READY_TO_SHIP'].includes(data.status)}><option>GHN</option><option>GHTK</option><option>VIETTEL_POST</option><option value="SELF">Tự giao</option><option value="OTHER">Khác</option></select></label><label>Mã vận đơn<input value={tracking} onChange={e=>setTracking(e.target.value)} placeholder="VD: GHN123456789" disabled={!['READY_TO_SHIP'].includes(data.status)}/></label>{data.trackingCode&&<small>Đã lưu: {data.shippingProvider||'OTHER'} · {data.trackingCode}</small>}<p className="seller-hint">Mã vận đơn được bắt buộc khi chuyển từ “Chờ lấy hàng” sang “Đang giao”.</p></section></aside></div>
 </SellerShell>;
}
