'use client';
import { useCallback, useEffect, useState } from 'react';
import { hasSellerSession, sellerApi } from '../lib/client-api';
import { SellerShell } from './seller-shell';

const money=(n:number)=>new Intl.NumberFormat('vi-VN').format(n)+'₫';
const date=(v:string)=>new Intl.DateTimeFormat('vi-VN',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v));
const STATUS:Record<string,string>={PENDING_PAYMENT:'Chờ thanh toán',PAID:'Đã thanh toán',CONFIRMED:'Đã xác nhận',PACKING:'Đang đóng gói',READY_TO_SHIP:'Chờ lấy hàng',SHIPPED:'Đang giao',DELIVERED:'Đã giao',COMPLETED:'Hoàn tất',CANCELLED:'Đã hủy',RETURN_REQUESTED:'Yêu cầu trả hàng',RETURN_APPROVED:'Đã duyệt trả',RETURNED:'Đang trả về',REFUND_PENDING:'Chờ hoàn tiền',REFUNDED:'Đã hoàn tiền',DISPUTED:'Khiếu nại'};
const TABS=[['','Tất cả'],['PAID','Đã thanh toán'],['CONFIRMED','Đã xác nhận'],['PACKING','Đóng gói'],['READY_TO_SHIP','Chờ giao'],['SHIPPED','Đang giao'],['DELIVERED','Đã giao'],['COMPLETED','Hoàn tất']];
type Row={_id:string;subOrderCode:string;orderCode:string;status:string;subtotal:number;shippingFee:number;sellerRevenue:number;createdAt:string;paymentMethod:string;paymentStatus:string;recipient?:{name:string;phone:string;province:string;district:string};itemCount:number;previewItems:Array<{_id:string;productName:string;image:string;quantity:number;variantSnapshot?:{attributes?:Record<string,string>}}>};
type Data={items:Row[];meta:{page:number;limit:number;total:number;totalPages:number};statusCounts:Record<string,number>};
export function SellerOrdersClient(){
  const [status,setStatus]=useState('');const [page,setPage]=useState(1);const [data,setData]=useState<Data|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
  const load=useCallback(async()=>{if(!hasSellerSession()){window.location.href='/login?next=%2Forders';return;}setLoading(true);setError('');try{const q=new URLSearchParams({page:String(page),limit:'12'});if(status)q.set('status',status);setData(await sellerApi<Data>('/seller/orders?'+q));}catch(e){setError(e instanceof Error?e.message:'Không tải được đơn');}finally{setLoading(false);}},[status,page]);useEffect(()=>{load();},[load]);
  return <SellerShell active="orders"><section className="seller-page-head"><div><span>ORDER MANAGEMENT</span><h1>Quản lý đơn hàng</h1><p>Mỗi dòng là SubOrder của riêng shop; seller khác không thể truy cập.</p></div><strong>{data?.meta.total??0} đơn</strong></section>
    <div className="seller-order-tabs">{TABS.map(([key,label])=><button className={status===key?'active':''} key={key||'all'} onClick={()=>{setStatus(key);setPage(1)}}>{label}{key&&<em>{data?.statusCounts?.[key]||0}</em>}</button>)}</div>
    {error&&<div className="seller-alert">{error}</div>}
    {loading?<div className="seller-loading">Đang tải đơn hàng…</div>:data?.items.length?<div className="seller-orders-list">{data.items.map(row=><article key={row._id} className="seller-order-card"><header><div><b>{row.subOrderCode}</b><small>Master: {row.orderCode} · {date(row.createdAt)}</small></div><span className={'seller-badge status-'+row.status.toLowerCase()}>{STATUS[row.status]||row.status}</span></header><div className="seller-order-body"><div className="seller-order-products">{row.previewItems.map(item=><div className="seller-order-product" key={item._id}><img src={item.image||'/products/fallback.svg'} alt=""/><div><b>{item.productName}</b><small>{Object.values(item.variantSnapshot?.attributes||{}).filter(Boolean).join(' · ')} · x{item.quantity}</small></div></div>)}</div><div className="seller-order-meta"><span>Người nhận <b>{row.recipient?.name||'—'}</b></span><span>Khu vực <b>{[row.recipient?.district,row.recipient?.province].filter(Boolean).join(', ')||'—'}</b></span><span>Thanh toán <b>{row.paymentMethod} · {row.paymentStatus}</b></span><span>Seller revenue <strong>{money(row.sellerRevenue)}</strong></span></div></div><footer><span>{row.itemCount} sản phẩm · Ship {money(row.shippingFee)}</span><a href={'/orders/'+encodeURIComponent(row.subOrderCode)}>Xử lý đơn →</a></footer></article>)}</div>:<div className="seller-empty"><h2>Chưa có đơn trong trạng thái này</h2><p>Tạo đơn từ Buyer Store bằng tài khoản buyer để test luồng xử lý seller.</p></div>}
    {data&&data.meta.totalPages>1&&<div className="seller-pagination"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>← Trước</button><span>Trang {page}/{data.meta.totalPages}</span><button disabled={page>=data.meta.totalPages} onClick={()=>setPage(p=>p+1)}>Sau →</button></div>}
  </SellerShell>;
}
