'use client';
import { useCallback, useEffect, useState } from 'react';
import { hasSellerSession, sellerApi } from '../lib/client-api';
import { SellerShell } from './seller-shell';
const money=(n:number)=>new Intl.NumberFormat('vi-VN').format(n)+'₫';
const date=(v:string)=>new Intl.DateTimeFormat('vi-VN',{dateStyle:'short',timeStyle:'short'}).format(new Date(v));
const STATUS:Record<string,string>={REQUESTED:'Chờ xử lý',APPROVED:'Đã duyệt',REJECTED:'Đã từ chối',RETURN_SHIPPED:'Buyer đã gửi trả',REFUND_PENDING:'Chờ hoàn tiền',REFUNDED:'Đã hoàn tiền',DISPUTED:'Khiếu nại'};
type Row={_id:string;requestCode:string;orderCode:string;subOrderCode:string;status:string;reason:string;refundAmount:number;createdAt:string;buyerId:string;items:Array<{productName:string;image:string;quantity:number}>};
type Data={items:Row[];meta:{total:number;page:number;totalPages:number}};
export function SellerReturnsClient(){const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[page,setPage]=useState(1);const load=useCallback(async()=>{if(!hasSellerSession()){location.href='/login?next=%2Freturns';return;}try{setData(await sellerApi<Data>(`/seller/returns?page=${page}&limit=20`));}catch(e){setError(e instanceof Error?e.message:'Không tải được yêu cầu trả hàng')}},[page]);useEffect(()=>{load()},[load]);return <SellerShell active="returns"><section className="seller-page-head"><div><span>AFTER SALES</span><h1>Trả hàng & hoàn tiền</h1><p>Xử lý yêu cầu theo đúng SubOrder của shop.</p></div><strong>{data?.meta.total||0} yêu cầu</strong></section>{error&&<div className="seller-alert">{error}</div>}{!data?<div className="seller-loading">Đang tải…</div>:data.items.length?<div className="seller-returns-list">{data.items.map(r=><article className="seller-return-card" key={r._id}><header><div><b>{r.requestCode}</b><small>{r.orderCode} · {r.subOrderCode} · {date(r.createdAt)}</small></div><span className={'seller-badge status-'+r.status.toLowerCase()}>{STATUS[r.status]||r.status}</span></header><div className="seller-return-body"><img src={r.items[0]?.image||'/products/fallback.svg'} alt=""/><div><b>{r.items[0]?.productName||'Sản phẩm'}</b><small>{r.items.reduce((n,i)=>n+i.quantity,0)} sản phẩm · {r.reason}</small></div><strong>{money(r.refundAmount)}</strong></div><footer><span>Giá trị dự kiến hoàn</span><a href={'/returns/'+r.requestCode}>Xử lý →</a></footer></article>)}</div>:<div className="seller-empty"><h2>Chưa có yêu cầu trả hàng</h2><p>Khi buyer gửi yêu cầu, chúng sẽ xuất hiện ở đây.</p></div>}{data&&data.meta.totalPages>1&&<div className="seller-pagination"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>← Trước</button><span>Trang {page}/{data.meta.totalPages}</span><button disabled={page>=data.meta.totalPages} onClick={()=>setPage(p=>p+1)}>Sau →</button></div>}</SellerShell>}
