'use client';
import { useCallback,useEffect,useState } from 'react';
import { hasSellerSession,sellerApi } from '../lib/client-api';
import { SellerShell } from './seller-shell';
type Member={_id:string;role:string;status:string;permissions:string[];user:{email:string;fullName:string}|null;createdAt:string};
type Data={shop:{name:string};items:Member[];availablePermissions:string[];roleDefaults:Record<string,string[]>};
export function SellerTeamClient(){const[data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const load=useCallback(async()=>{if(!hasSellerSession()){location.href='/login?next=%2Fteam';return;}try{setData(await sellerApi<Data>('/seller/access/team'));setError('')}catch(e){setError(e instanceof Error?e.message:'Không tải được team')}},[]);useEffect(()=>{load()},[load]);
async function add(){const email=prompt('Email user đã đăng ký XIII:');if(!email)return;const role=(prompt('Role: MANAGER hoặc STAFF','STAFF')||'STAFF').toUpperCase();if(!['MANAGER','STAFF'].includes(role)){setError('Role không hợp lệ');return;}setBusy(true);try{await sellerApi('/seller/access/team',{method:'POST',body:JSON.stringify({email,role})});await load()}catch(e){setError(e instanceof Error?e.message:'Không thêm được thành viên')}finally{setBusy(false)}}
async function edit(m:Member){if(m.role==='OWNER'||!data)return;const role=(prompt('Role mới: MANAGER hoặc STAFF',m.role)||m.role).toUpperCase();const status=(prompt('Trạng thái: ACTIVE hoặc SUSPENDED',m.status)||m.status).toUpperCase();if(!['MANAGER','STAFF'].includes(role)||!['ACTIVE','SUSPENDED'].includes(status))return;const defaultPermissions=data.roleDefaults[role]||[];const raw=prompt('Permissions, ngăn cách bằng dấu phẩy. Có thể giữ nguyên hoặc tinh chỉnh:',m.permissions.length?m.permissions.join(','):defaultPermissions.join(','));if(raw===null)return;const permissions=raw.split(',').map(x=>x.trim()).filter(Boolean);const invalid=permissions.filter(p=>!data.availablePermissions.includes(p));if(invalid.length){setError(`Permission không hợp lệ: ${invalid.join(', ')}`);return;}setBusy(true);try{await sellerApi(`/seller/access/team/${m._id}`,{method:'PATCH',body:JSON.stringify({role,status,permissions})});await load()}catch(e){setError(e instanceof Error?e.message:'Không cập nhật được')}finally{setBusy(false)}}
async function remove(m:Member){if(!confirm(`Gỡ ${m.user?.email||'thành viên'} khỏi shop?`))return;setBusy(true);try{await sellerApi(`/seller/access/team/${m._id}`,{method:'DELETE'});await load()}catch(e){setError(e instanceof Error?e.message:'Không gỡ được thành viên')}finally{setBusy(false)}}
return <SellerShell active="team"><section className="seller-page-head"><div><span>SHOP ACCESS CONTROL</span><h1>Nhân sự & phân quyền</h1><p>Owner, Manager và Staff dùng cùng một shop nhưng chỉ truy cập đúng nghiệp vụ được cấp.</p></div><button className="seller-primary" disabled={busy} onClick={add}>+ Thêm thành viên</button></section>{error&&<div className="seller-alert">{error}</div>}<section className="seller-panel"><div className="seller-panel-head"><div><span>{data?.shop.name||'SHOP TEAM'}</span><h2>{data?.items.length||0} thành viên</h2></div><small>OWNER có toàn quyền; Manager/Staff có thể tinh chỉnh permission trực tiếp khi bấm Sửa.</small></div><div className="seller-table-wrap"><table className="seller-table"><thead><tr><th>Thành viên</th><th>Role</th><th>Trạng thái</th><th>Quyền</th><th></th></tr></thead><tbody>{data?.items.map(m=><tr key={m._id}><td><b>{m.user?.fullName||'Unknown user'}</b><small>{m.user?.email||'—'}</small></td><td><span className="seller-badge">{m.role}</span></td><td><span className={'seller-badge '+(m.status==='ACTIVE'?'finance-paid':'finance-requested')}>{m.status}</span></td><td><small>{m.permissions.join(' · ')}</small></td><td>{m.role!=='OWNER'&&<div style={{display:'flex',gap:8}}><button className="seller-link-btn" onClick={()=>edit(m)} disabled={busy}>Sửa</button><button className="seller-link-btn" onClick={()=>remove(m)} disabled={busy}>Gỡ</button></div>}</td></tr>)}</tbody></table></div>{!data?.items.length&&<div className="seller-empty">Chưa có dữ liệu team.</div>}</section><section className="seller-panel" style={{marginTop:16}}><div className="seller-panel-head"><div><span>PERMISSION MODEL</span><h2>Quyền có thể cấp</h2></div></div><p style={{lineHeight:1.8,color:'#69706a'}}>{data?.availablePermissions.join(' · ')}</p></section></SellerShell>}
