'use client';
import { useCallback, useEffect, useState } from 'react';
import { hasSellerSession, sellerApi } from '../lib/client-api';
import { SellerShell } from './seller-shell';
const money=(n:number)=>new Intl.NumberFormat('vi-VN').format(n)+'₫';
const date=(v?:string)=>v?new Intl.DateTimeFormat('vi-VN',{dateStyle:'short',timeStyle:'short'}).format(new Date(v)):'—';
const TYPE:Record<string,string>={SALE_GROSS:'Doanh thu đơn hàng',PLATFORM_FEE:'Phí nền tảng',REFUND_DEBIT:'Hoàn tiền buyer',FEE_REVERSAL:'Hoàn phí nền tảng',WITHDRAWAL:'Rút tiền',ADJUSTMENT:'Điều chỉnh'};
type Summary={pendingBalance:number;availableLedgerBalance:number;withdrawalHold:number;availableBalance:number;negativeBalance:number;settings:{commissionRateBps:number;settlementDelayDays:number;minWithdrawalAmount:number;maxWithdrawalAmount:number};latestWithdrawal?:Withdrawal|null};
type Ledger={_id:string;type:string;amount:number;status:string;referenceCode:string;description:string;availableAt?:string;createdAt:string};
type Withdrawal={_id:string;withdrawalCode:string;amount:number;status:string;payoutSnapshot:{bankCode?:string;bankName?:string;accountName?:string;accountNumberLast4?:string};externalReference?:string;rejectionReason?:string;createdAt:string};
type Payout={_id:string;bankCode:string;bankName:string;accountName:string;accountNumberMasked:string;status:string}|null;
type PageData<T>={items:T[];meta:{total:number}};
export function SellerFinanceClient(){
  const [summary,setSummary]=useState<Summary|null>(null),[ledger,setLedger]=useState<Ledger[]>([]),[withdrawals,setWithdrawals]=useState<Withdrawal[]>([]),[payout,setPayout]=useState<Payout>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{if(!hasSellerSession()){location.href='/login?next=%2Ffinance';return;}try{const [s,l,w,p]=await Promise.all([sellerApi<Summary>('/seller/finance/summary'),sellerApi<PageData<Ledger>>('/seller/finance/ledger?limit=50'),sellerApi<PageData<Withdrawal>>('/seller/finance/withdrawals?limit=20'),sellerApi<Payout>('/seller/finance/payout-account')]);setSummary(s);setLedger(l.items);setWithdrawals(w.items);setPayout(p)}catch(e){setError(e instanceof Error?e.message:'Không tải được tài chính')}},[]);useEffect(()=>{load()},[load]);
  async function savePayout(){const bankCode=prompt('Mã ngân hàng (VD: VCB, MB, ACB):',payout?.bankCode||'');if(!bankCode)return;const bankName=prompt('Tên ngân hàng:',payout?.bankName||'')||'';const accountName=prompt('Tên chủ tài khoản:',payout?.accountName||'');if(!accountName)return;const accountNumber=prompt('Số tài khoản mới:','');if(!accountNumber)return;setBusy(true);try{await sellerApi('/seller/finance/payout-account',{method:'PATCH',body:JSON.stringify({bankCode,bankName,accountName,accountNumber})});await load()}catch(e){setError(e instanceof Error?e.message:'Không lưu được tài khoản')}finally{setBusy(false)}}
  async function withdraw(){if(!summary)return;const raw=prompt(`Số tiền muốn rút. Khả dụng: ${money(summary.availableBalance)}`,String(Math.min(summary.availableBalance,Math.max(summary.settings.minWithdrawalAmount,100000))));if(!raw)return;const amount=Number(raw.replace(/\D/g,''));if(!amount)return;setBusy(true);try{await sellerApi('/seller/finance/withdrawals',{method:'POST',body:JSON.stringify({amount})});await load()}catch(e){setError(e instanceof Error?e.message:'Không tạo được yêu cầu rút tiền')}finally{setBusy(false)}}
  async function cancel(code:string){if(!confirm('Hủy yêu cầu rút tiền này?'))return;setBusy(true);try{await sellerApi(`/seller/finance/withdrawals/${code}/cancel`,{method:'POST',body:'{}'});await load()}catch(e){setError(e instanceof Error?e.message:'Không hủy được yêu cầu')}finally{setBusy(false)}}
  return <SellerShell active="finance"><section className="seller-page-head"><div><span>SELLER FINANCE</span><h1>Tài chính & đối soát</h1><p>Số dư được tính từ ledger. Tiền đơn hoàn tất sẽ chờ đối soát trước khi khả dụng.</p></div><button className="seller-primary" disabled={busy||!summary||summary.availableBalance<summary.settings.minWithdrawalAmount} onClick={withdraw}>Rút tiền</button></section>{error&&<div className="seller-alert">{error}</div>}
  <div className="seller-kpis finance-kpis"><article><small>Số dư khả dụng</small><strong>{summary?money(summary.availableBalance):'—'}</strong><span>Có thể tạo withdrawal</span></article><article><small>Đang chờ đối soát</small><strong>{summary?money(summary.pendingBalance):'—'}</strong><span>{summary?.settings.settlementDelayDays??'—'} ngày settlement</span></article><article><small>Đang giữ để rút</small><strong>{summary?money(summary.withdrawalHold):'—'}</strong><span>Requested / Approved / Processing</span></article><article><small>Commission hiện tại</small><strong>{summary?(summary.settings.commissionRateBps/100).toFixed(2)+'%':'—'}</strong><span>Tính khi checkout</span></article></div>
  <div className="seller-finance-grid"><section className="seller-panel"><div className="seller-panel-head"><div><span>PAYOUT</span><h2>Tài khoản nhận tiền</h2></div><button className="seller-link-btn" disabled={busy} onClick={savePayout}>{payout?'Cập nhật':'Thêm tài khoản'}</button></div>{payout?<div className="seller-bank-card"><div><b>{payout.bankName||payout.bankCode}</b><span>{payout.accountNumberMasked}</span></div><small>{payout.accountName}</small></div>:<div className="seller-empty compact"><b>Chưa có tài khoản ngân hàng</b><p>Thêm tài khoản trước khi tạo yêu cầu rút tiền.</p></div>}</section><section className="seller-panel"><div className="seller-panel-head"><div><span>WITHDRAWAL POLICY</span><h2>Quy tắc rút tiền</h2></div></div><div className="seller-finance-rules"><div><span>Tối thiểu</span><b>{summary?money(summary.settings.minWithdrawalAmount):'—'}</b></div><div><span>Tối đa / yêu cầu</span><b>{summary?money(summary.settings.maxWithdrawalAmount):'—'}</b></div><div><span>Số dư ledger</span><b>{summary?money(summary.availableLedgerBalance):'—'}</b></div></div></section></div>
  <section className="seller-panel finance-section"><div className="seller-panel-head"><div><span>WITHDRAWALS</span><h2>Lịch sử rút tiền</h2></div></div>{withdrawals.length?<div className="seller-table-wrap"><table className="seller-table"><thead><tr><th>Mã</th><th>Số tiền</th><th>Tài khoản</th><th>Trạng thái</th><th>Ngày tạo</th><th></th></tr></thead><tbody>{withdrawals.map(w=><tr key={w._id}><td><b>{w.withdrawalCode}</b>{w.externalReference&&<small>{w.externalReference}</small>}</td><td><b>{money(w.amount)}</b></td><td>{w.payoutSnapshot.bankCode} · •••• {w.payoutSnapshot.accountNumberLast4}</td><td><span className={'seller-badge finance-'+w.status.toLowerCase()}>{w.status}</span>{w.rejectionReason&&<small>{w.rejectionReason}</small>}</td><td>{date(w.createdAt)}</td><td>{w.status==='REQUESTED'&&<button className="seller-link-btn" disabled={busy} onClick={()=>cancel(w.withdrawalCode)}>Hủy</button>}</td></tr>)}</tbody></table></div>:<div className="seller-empty compact">Chưa có yêu cầu rút tiền.</div>}</section>
  <section className="seller-panel finance-section"><div className="seller-panel-head"><div><span>IMMUTABLE AMOUNTS</span><h2>Seller ledger</h2></div><small>Trạng thái PENDING chỉ chuyển sang AVAILABLE khi hết kỳ đối soát.</small></div>{ledger.length?<div className="seller-table-wrap"><table className="seller-table"><thead><tr><th>Ngày</th><th>Loại</th><th>Tham chiếu</th><th>Trạng thái</th><th>Số tiền</th></tr></thead><tbody>{ledger.map(x=><tr key={x._id}><td>{date(x.createdAt)}</td><td><b>{TYPE[x.type]||x.type}</b><small>{x.description}</small></td><td>{x.referenceCode||'—'}</td><td><span className={'seller-badge '+(x.status==='AVAILABLE'?'finance-paid':'finance-requested')}>{x.status}</span>{x.status==='PENDING'&&<small>Khả dụng {date(x.availableAt)}</small>}</td><td className={x.amount<0?'money-negative':'money-positive'}><b>{x.amount>0?'+':''}{money(x.amount)}</b></td></tr>)}</tbody></table></div>:<div className="seller-empty compact">Ledger chưa có giao dịch. Hoàn tất một đơn để tạo settlement entry.</div>}</section></SellerShell>}
