'use client';
import { useEffect, useMemo, useState } from 'react';
import { hasSellerSession, sellerApi } from '../lib/client-api';
import { SellerShell } from './seller-shell';

const money=(n:number)=>new Intl.NumberFormat('vi-VN').format(Math.round(n))+'₫';
const pct=(n:number)=>`${Number(n||0).toFixed(2)}%`;
const d=(date:Date)=>date.toISOString().slice(0,10);

type Trend={date:string;orders:number;grossSales:number;netRevenue:number;views:number;refunds:number};
type Analytics={range:{from:string;to:string;days:number};kpis:{orders:number;grossSales:number;sellerRevenueBeforeRefund:number;refundAmount:number;estimatedNetRevenue:number;platformFees:number;sellerDiscount:number;averageOrderValue:number;productViews:number;orderPerViewRate:number;returnRequests:number;returnRate:number;reviewCount:number;reviewAverage:number};trend:Trend[];statusCounts:Record<string,number>;topProducts:Array<{productId:string;name:string;slug:string;units:number;revenue:number;views:number;orderPerViewRate:number}>;inventory:{totalSkus:number;availableUnits:number;reservedUnits:number;soldUnits:number;lowStockSkus:number;outOfStockSkus:number;retailInventoryValue:number};finance:{availableLedger:number;pendingLedger:number;withdrawalRequested:number;withdrawalProcessing:number;totalWithdrawn:number};catalog:{totalProducts:number;activeProducts:number;lifetimeViews:number;lifetimeSold:number};reviews:{distribution:Record<string,number>}};

function csvCell(value:unknown){const s=String(value??'');return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}
function downloadReport(data:Analytics){
  const rows:unknown[][]=[['XIII SELLER ANALYTICS'],['From',data.range.from,'To',data.range.to],[],['KPI','Value'],['Orders',data.kpis.orders],['Gross sales',data.kpis.grossSales],['Estimated net revenue',data.kpis.estimatedNetRevenue],['Platform fees',data.kpis.platformFees],['Refund amount',data.kpis.refundAmount],['Product views',data.kpis.productViews],['Order / product view rate',data.kpis.orderPerViewRate],[],['Daily'],['Date','Orders','Gross sales','Seller revenue','Views','Refunds'],...data.trend.map(x=>[x.date,x.orders,x.grossSales,x.netRevenue,x.views,x.refunds]),[],['Top products'],['Product','Units','Revenue','Views','Order/View %'],...data.topProducts.map(x=>[x.name,x.units,x.revenue,x.views,x.orderPerViewRate])];
  const blob=new Blob(['\ufeff'+rows.map(r=>r.map(csvCell).join(',')).join('\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`XIII-seller-report-${data.range.from}-${data.range.to}.csv`;a.click();URL.revokeObjectURL(url);
}
function RevenueChart({rows}:{rows:Trend[]}){const max=Math.max(1,...rows.map(x=>x.grossSales));return <div className="analytics-chart">{rows.map(row=><div className="analytics-bar-col" key={row.date} title={`${row.date}: ${money(row.grossSales)}`}><div className="analytics-bar-track"><i style={{height:`${Math.max(row.grossSales?5:0,(row.grossSales/max)*100)}%`}}/></div><small>{row.date.slice(5)}</small></div>)}</div>}

export function SellerAnalyticsClient(){
  const [days,setDays]=useState(30);const [data,setData]=useState<Analytics|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
  const range=useMemo(()=>{const to=new Date();const from=new Date(to.getTime()-(days-1)*86400000);return{from:d(from),to:d(to)}},[days]);
  useEffect(()=>{if(!hasSellerSession()){location.href='/login';return;}setLoading(true);setError('');sellerApi<Analytics>(`/seller/analytics?from=${range.from}&to=${range.to}`).then(setData).catch(e=>setError(e instanceof Error?e.message:'Không tải được analytics')).finally(()=>setLoading(false));},[range.from,range.to]);
  return <SellerShell active="analytics">
    <section className="seller-page-head"><div><span>ANALYTICS & REPORTS</span><h1>Phân tích shop</h1><p>Doanh thu, đơn hàng, product views, tồn kho, hoàn tiền và finance đều lấy từ dữ liệu thật trong hệ thống.</p></div><div className="analytics-actions"><select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>7 ngày</option><option value={30}>30 ngày</option><option value={90}>90 ngày</option></select><button className="seller-primary" disabled={!data} onClick={()=>data&&downloadReport(data)}>Xuất CSV</button></div></section>
    {error&&<div className="seller-alert">{error}</div>}{loading&&<div className="analytics-loading">Đang tổng hợp dữ liệu…</div>}
    {data&&<>
      <div className="seller-kpis analytics-kpis"><article><small>GMV shop</small><strong>{money(data.kpis.grossSales)}</strong><span>{data.kpis.orders} đơn hợp lệ</span></article><article><small>Doanh thu ước tính sau phí/hoàn</small><strong>{money(data.kpis.estimatedNetRevenue)}</strong><span>Phí nền tảng {money(data.kpis.platformFees)}</span></article><article><small>Product views</small><strong>{new Intl.NumberFormat('vi-VN').format(data.kpis.productViews)}</strong><span>Đơn / lượt xem: {pct(data.kpis.orderPerViewRate)}</span></article><article><small>Return rate</small><strong>{pct(data.kpis.returnRate)}</strong><span>{data.kpis.returnRequests} yêu cầu · hoàn {money(data.kpis.refundAmount)}</span></article></div>
      <div className="analytics-grid-main"><section className="seller-panel analytics-card"><div className="seller-panel-head"><div><span>REVENUE TREND</span><h2>Doanh thu theo ngày</h2></div><b>{data.range.from} → {data.range.to}</b></div><RevenueChart rows={data.trend}/><div className="analytics-legend"><span>GMV shop</span><span>{money(data.kpis.grossSales)}</span></div></section><section className="seller-panel analytics-card"><div className="seller-panel-head"><div><span>QUALITY</span><h2>Hiệu quả bán hàng</h2></div></div><div className="analytics-stat-list"><div><span>Giá trị đơn trung bình</span><b>{money(data.kpis.averageOrderValue)}</b></div><div><span>Seller discount</span><b>{money(data.kpis.sellerDiscount)}</b></div><div><span>Rating trong kỳ</span><b>{data.kpis.reviewAverage||'—'} / 5</b></div><div><span>Review mới</span><b>{data.kpis.reviewCount}</b></div><div><span>Doanh thu trước refund</span><b>{money(data.kpis.sellerRevenueBeforeRefund)}</b></div></div></section></div>
      <div className="seller-grid-2 analytics-lower"><section className="seller-panel"><div className="seller-panel-head"><div><span>TOP PRODUCTS</span><h2>Sản phẩm dẫn đầu</h2></div></div><div className="analytics-table"><div className="analytics-table-head"><span>Sản phẩm</span><span>SL</span><span>Doanh thu</span><span>View</span></div>{data.topProducts.length?data.topProducts.map((p,i)=><div className="analytics-table-row" key={p.productId}><span><b>#{i+1} {p.name}</b><small>{pct(p.orderPerViewRate)} order/view</small></span><span>{p.units}</span><span>{money(p.revenue)}</span><span>{p.views}</span></div>):<p className="analytics-empty">Chưa có doanh số trong kỳ.</p>}</div></section><section className="seller-panel"><div className="seller-panel-head"><div><span>INVENTORY</span><h2>Sức khỏe kho</h2></div><a href="/inventory">Mở kho →</a></div><div className="analytics-mini-grid"><div><small>SKU</small><b>{data.inventory.totalSkus}</b></div><div><small>Có sẵn</small><b>{data.inventory.availableUnits}</b></div><div><small>Sắp hết</small><b>{data.inventory.lowStockSkus}</b></div><div><small>Hết hàng</small><b>{data.inventory.outOfStockSkus}</b></div></div><div className="analytics-note">Giá trị tồn theo giá bán hiện tại: <b>{money(data.inventory.retailInventoryValue)}</b></div></section></div>
      <div className="seller-grid-2 analytics-lower"><section className="seller-panel"><div className="seller-panel-head"><div><span>FINANCE</span><h2>Đối soát & rút tiền</h2></div><a href="/finance">Chi tiết →</a></div><div className="analytics-stat-list"><div><span>Ledger khả dụng</span><b>{money(data.finance.availableLedger)}</b></div><div><span>Ledger chờ đối soát</span><b>{money(data.finance.pendingLedger)}</b></div><div><span>Withdrawal requested</span><b>{money(data.finance.withdrawalRequested)}</b></div><div><span>Đang xử lý</span><b>{money(data.finance.withdrawalProcessing)}</b></div><div><span>Đã rút</span><b>{money(data.finance.totalWithdrawn)}</b></div></div></section><section className="seller-panel"><div className="seller-panel-head"><div><span>CATALOG</span><h2>Catalog lifetime</h2></div><a href="/products">Sản phẩm →</a></div><div className="analytics-mini-grid"><div><small>Tổng product</small><b>{data.catalog.totalProducts}</b></div><div><small>Đang bán</small><b>{data.catalog.activeProducts}</b></div><div><small>Lifetime views</small><b>{new Intl.NumberFormat('vi-VN').format(data.catalog.lifetimeViews)}</b></div><div><small>Lifetime sold</small><b>{new Intl.NumberFormat('vi-VN').format(data.catalog.lifetimeSold)}</b></div></div></section></div>
    </>}
  </SellerShell>;
}
