'use client';
import {useEffect,useRef,useState} from 'react';
import {IMAGE_ACCEPT,IMAGE_FORMATS,IMAGE_LIMITS,prepareImage,type ImagePurpose} from './image-upload';
import {drawImageEdit,exportImageEdit,loadImage,ORIGINAL_EDIT,type ImageEdit} from './image-editor';
type Props={label:string;purpose:ImagePurpose;upload:(file:File)=>Promise<string>;onUploaded:(url:string)=>void;onBusyChange?:(busy:boolean)=>void;onPendingChange?:(pending:boolean)=>void;multiple?:boolean;maxFiles?:number;disabled?:boolean};
export function ImageUploader({label,purpose,upload,onUploaded,onBusyChange,onPendingChange,multiple=false,maxFiles=20,disabled=false}:Props){
 const [files,setFiles]=useState<File[]>([]),[index,setIndex]=useState(0),[edit,setEdit]=useState<ImageEdit>({...ORIGINAL_EDIT}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const savedEdits=useRef(new Map<File,ImageEdit>()),pendingCallback=useRef(onPendingChange);pendingCallback.current=onPendingChange;
 const lock=useRef(false),mounted=useRef(true),canvas=useRef<HTMLCanvasElement>(null);const [source,setSource]=useState<HTMLImageElement|null>(null);const file=files[index];
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false}},[]);
 useEffect(()=>{pendingCallback.current?.(files.length>0);return()=>pendingCallback.current?.(false)},[files.length]);
 useEffect(()=>{let active=true;setSource(null);if(file)loadImage(file).then(img=>{if(active)setSource(img)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[file]);
 useEffect(()=>{if(source&&canvas.current){try{drawImageEdit(canvas.current,source,edit,true)}catch(e){setError(e instanceof Error?e.message:'Không xem trước được ảnh')}}},[source,edit]);
 function markBusy(value:boolean){lock.current=value;if(mounted.current)setBusy(value);onBusyChange?.(value)}
 async function choose(selected:File[]){if(lock.current||disabled||!selected.length)return;markBusy(true);setError('');setNotice('');const valid:File[]=[],errors:string[]=[];
 try{if(selected.length>maxFiles)throw new Error('Chọn tối đa '+maxFiles+' ảnh cho mục này.');for(const f of selected){try{valid.push(await prepareImage(f,purpose))}catch(e){errors.push(f.name+': '+(e instanceof Error?e.message:'File không hợp lệ'))}}if(mounted.current){savedEdits.current.clear();setFiles(valid);setIndex(0);setEdit({...ORIGINAL_EDIT});setError(errors.join(' · '));}}catch(e){if(mounted.current)setError(e instanceof Error?e.message:'Không chọn được ảnh')}finally{markBusy(false)}}
 function reset(){savedEdits.current.clear();setFiles([]);setIndex(0);setEdit({...ORIGINAL_EDIT});setSource(null)}
 async function applyEdit(){if(!file||lock.current)return;markBusy(true);setError('');try{const result=await exportImageEdit(file,edit);await prepareImage(result,purpose);if(mounted.current){savedEdits.current.delete(file);setFiles(current=>current.map((f,i)=>i===index?result:f));setEdit({...ORIGINAL_EDIT});setNotice('Đã áp dụng chỉnh sửa. Ảnh chưa được tải lên.')}}catch(e){if(mounted.current)setError(e instanceof Error?e.message:'Không chỉnh được ảnh')}finally{markBusy(false)}}
 async function send(){if(!files.length||lock.current||disabled)return;if(files.length>maxFiles){setError('Chỉ còn chỗ cho '+maxFiles+' ảnh. Bỏ ảnh đã chọn rồi chọn lại.');return;}markBusy(true);setError('');setNotice('');const failures:File[]=[],errors:string[]=[];let count=0;
 try{for(let i=0;i<files.length;i++){let ready=files[i];try{ready=await exportImageEdit(files[i],i===index?edit:savedEdits.current.get(files[i])||ORIGINAL_EDIT);const url=await upload(ready);if(!mounted.current)return;onUploaded(url);count++;}catch(e){failures.push(ready);savedEdits.current.delete(files[i]);errors.push(files[i].name+': '+(e instanceof Error?e.message:'Không tải được ảnh'))}}if(mounted.current){setFiles(failures);setIndex(0);setEdit({...ORIGINAL_EDIT});setNotice(count?'Đã tải '+count+'/'+files.length+' ảnh.':'');setError(errors.join(' · '));}}finally{markBusy(false)}}
 const locked=busy||disabled;const animated=file?.type==='image/gif';
 return <div className="image-uploader" role="group" aria-label={label}>
 <label>{label}<input type="file" accept={IMAGE_ACCEPT} multiple={multiple} disabled={locked||maxFiles<1} onChange={e=>{const list=Array.from(e.currentTarget.files||[]);e.currentTarget.value='';void choose(list)}}/></label>
 <small>{IMAGE_FORMATS} · Tối đa {IMAGE_LIMITS[purpose]} MB/ảnh. Xem trước rồi bấm tải; ảnh chưa chỉnh giữ nguyên chất lượng.</small>
 {files.length>0&&<div className="image-editor"><div className="image-editor-queue">{files.map((f,i)=><button type="button" disabled={locked} key={i} aria-pressed={i===index} onClick={()=>{if(file)savedEdits.current.set(file,edit);setIndex(i);setEdit(savedEdits.current.get(f)||{...ORIGINAL_EDIT})}}>{i+1}. {f.name}</button>)}</div>
 <canvas ref={canvas} aria-label="Xem trước vùng ảnh sẽ tải"/>{animated&&<p>GIF được tải nguyên để giữ chuyển động; bản xem trước là một khung hình, không cắt hoặc xoay.</p>}
 {!animated&&<div className="image-editor-controls"><button type="button" disabled={locked} onClick={()=>setEdit(e=>({...e,rotation:((e.rotation+90)%360) as ImageEdit['rotation']}))}>Xoay 90°</button><label>Tỷ lệ cắt<select value={edit.ratio} disabled={locked} onChange={e=>setEdit(v=>({...v,ratio:Number(e.target.value),zoom:1,x:0,y:0}))}><option value={0}>Giữ tỷ lệ gốc</option><option value={1}>Vuông 1:1 — logo</option><option value={0.8}>Dọc 4:5 — sản phẩm</option><option value={16/9}>Ngang 16:9 — banner</option><option value={3}>Ngang 3:1 — banner shop</option><option value={9/16}>Dọc 9:16 — điện thoại</option></select></label>
 <label>Phóng vùng cắt<input type="range" min={1} max={3} step={0.05} value={edit.zoom} disabled={locked} onChange={e=>setEdit(v=>({...v,zoom:Number(e.target.value)}))}/></label><label>Dịch ngang<input type="range" min={-100} max={100} value={edit.x} disabled={locked} onChange={e=>setEdit(v=>({...v,x:Number(e.target.value)}))}/></label><label>Dịch dọc<input type="range" min={-100} max={100} value={edit.y} disabled={locked} onChange={e=>setEdit(v=>({...v,y:Number(e.target.value)}))}/></label>
 <button type="button" disabled={locked} onClick={()=>void applyEdit()}>Áp dụng chỉnh sửa</button><button type="button" disabled={locked} onClick={()=>setEdit({...ORIGINAL_EDIT})}>Đặt lại vùng cắt</button><small>Ảnh đã chỉnh xuất PNG, giữ nền trong suốt. Vùng cắt được giữ riêng cho từng ảnh trong danh sách.</small></div>}
 <div className="image-editor-actions"><button type="button" disabled={locked} onClick={()=>void send()}>Tải {files.length} ảnh lên</button><button type="button" disabled={locked} onClick={reset}>Bỏ ảnh đã chọn</button></div></div>}
 {busy&&<p role="status">Đang xử lý ảnh…</p>}{notice&&<p role="status">{notice}</p>}{error&&<p role="alert">{error}</p>}
 </div>;
}
