'use client';

import { useEffect, useState } from 'react';
import { clientApi, hasSession } from '../lib/client-api';

type Order={orderCode:string;status:string;paymentMethod:string;paymentStatus:string;subtotal:number;shippingFee:number;discountAmount:number;totalAmount:number;shippingAddress:Record<string,string>;subOrders:Array<{_id:string;subOrderCode:string;status:string;subtotal:number;shippingFee:number;shop:null|{name:string;verified:boolean};items:Array<{_id:string;productName:string;image:string;quantity:number;unitPrice:number;totalPrice:number;variantSnapshot:{sku?:string;attributes?:Record<string,string>}}>}>};
const money=(n:number)=>new Intl.NumberFormat('vi-VN').format(n)+'₫';

export function OrderSuccessClient({orderCode}:{orderCode:string}){
  const [order,setOrder]=useState<Order|null>(null);const [message,setMessage]=useState('');
  useEffect(()=>{if(!hasSession()){setMessage('Bạn cần đăng nhập để xem đơn hàng.');return;}clientApi<Order>('/orders/'+encodeURIComponent(orderCode)).then(setOrder).catch(err=>setMessage(err instanceof Error?err.message:'Không tải được đơn hàng'));},[orderCode]);
  if(message)return <section className="cart-state"><h1>Không thể mở đơn hàng</h1><p>{message}</p><a className="cart-primary-link" href="/login">Đăng nhập</a></section>;
  if(!order)return <section className="cart-state"><div className="cart-spinner"/><b>Đang tải đơn hàng…</b></section>;
  const a=order.shippingAddress;
  return <div className="success-wrap"><section className="success-hero"><div className="success-check">✓</div><span>ĐẶT HÀNG THÀNH CÔNG</span><h1>Cảm ơn bạn.</h1><p>Đơn <b>{order.orderCode}</b> đã được tạo. Tồn kho của các SKU đã được giữ trong giao dịch checkout.</p><div className="success-status"><span>Trạng thái</span><b>{order.status}</b><span>Thanh toán</span><b>{order.paymentMethod} · {order.paymentStatus}</b></div></section><div className="success-grid"><section>{order.subOrders.map(sub=><article className="success-shop" key={sub._id}><header><div><b>{sub.shop?.name||'Shop'} {sub.shop?.verified?'✓':''}</b><small>{sub.subOrderCode}</small></div><strong>{sub.status}</strong></header>{sub.items.map(item=><div className="success-item" key={item._id}><img src={item.image||'/products/fallback.svg'} alt={item.productName}/><div><b>{item.productName}</b><small>{Object.values(item.variantSnapshot?.attributes||{}).join(' · ')} · x{item.quantity}</small></div><strong>{money(item.totalPrice)}</strong></div>)}<footer><span>Phí ship {money(sub.shippingFee)}</span><b>{money(sub.subtotal+sub.shippingFee)}</b></footer></article>)}</section><aside className="success-side"><div className="success-box"><h2>Giao đến</h2><b>{a.recipientName} · {a.phone}</b><p>{a.addressLine}, {a.ward}, {a.district}, {a.province}</p></div><div className="success-box"><h2>Tổng đơn</h2><div><span>Tạm tính</span><b>{money(order.subtotal)}</b></div><div><span>Vận chuyển</span><b>{money(order.shippingFee)}</b></div><div><span>Giảm giá</span><b>−{money(order.discountAmount)}</b></div><hr/><div className="final"><span>Thanh toán</span><b>{money(order.totalAmount)}</b></div></div><a className="success-primary" href={"/account/orders/"+encodeURIComponent(order.orderCode)}>Xem chi tiết đơn</a><a className="success-secondary" href="/account/orders">Tất cả đơn mua</a><a className="success-secondary" href="/search">Tiếp tục mua sắm</a></aside></div></div>;
}
