'use client';
import { useCallback, useEffect, useState } from 'react';
import { clientApi, hasSession } from '../lib/client-api';
const money=(n:number)=>new Intl.NumberFormat('vi-VN').format(n)+'₫';
const date=(v:string)=>new Intl.DateTimeFormat('vi-VN',{dateStyle:'short',timeStyle:'short'}).format(new Date(v));
const LABEL:Record<string,string>={REQUESTED:'Chờ shop xử lý',APPROVED:'Đã chấp nhận',REJECTED:'Bị từ chối',RETURN_SHIPPED:'Đang gửi trả',REFUND_PENDING:'Chờ hoàn tiền',REFUNDED:'Đã hoàn tiền',DISPUTED:'Đang khiếu nại'};
type Row={_id:string;requestCode:string;orderCode:string;subOrderCode:string;status:string;reason:string;refundAmount:number;createdAt:string;shop?:{name:string;verified:boolean};items:Array<{productName:string;image:string;quantity:number}>};
type Data={items:Row[];meta:{total:number}};
export function ReturnsClient(){const [mounted,setMounted]=useState(false);useEffect(()=>setMounted(true),[]);const [data,setData]=useState<Data|null>(null),[error,setError]=useState('');const load=useCallback(async()=>{if(!hasSession())return;try{setData(await clientApi<Data>('/returns'));}catch(e){setError(e instanceof Error?e.message:'Không tải được yêu cầu');}},[]);useEffect(()=>{load()},[load]);if(!mounted)return <section className="orders-loading" role="status"><div className="cart-spinner"/><b>Đang tải…</b></section>;if(!hasSession())return <section className="orders-state"><h1>Trả hàng & hoàn tiền</h1><p>Đăng nhập để xem yêu cầu hậu mãi.</p><a href="/login?next=%2Faccount%2Freturns">Đăng nhập</a></section>;
return <div className="account-layout"><aside className="account-sidebar"><div className="account-user"><span>CM</span><div><b>Tài khoản XIII</b><small>Buyer Center</small></div></div><nav><a href="/account/orders">Đơn mua</a><a href="/account/returns" className="active">Trả hàng & hoàn tiền</a><a href="/help">Trợ giúp</a><a href="/checkout">Địa chỉ</a><a href="/wishlist">Yêu thích</a></nav></aside><section className="orders-main"><header className="orders-heading"><div><span>AFTER SALES</span><h1>Trả hàng & hoàn tiền</h1><p>Theo dõi yêu cầu trả hàng, vận đơn trả và trạng thái hoàn tiền.</p></div><b>{data?.meta.total||0} yêu cầu</b></header>{error&&<div className="orders-alert">{error}</div>}{!data?<div className="orders-loading"><b>Đang tải…</b></div>:data.items.length?<div className="return-list">{data.items.map(r=><article className="return-card" key={r._id}><header><div><b>{r.shop?.name||'Shop'} {r.shop?.verified?'✓':''}</b><small>{r.requestCode} · {date(r.createdAt)}</small></div><span className={'return-status '+r.status.toLowerCase()}>{LABEL[r.status]||r.status}</span></header><div className="return-preview"><img src={r.items[0]?.image||'/products/fallback.svg'} alt=""/><div><b>{r.items[0]?.productName||'Sản phẩm'}</b><small>{r.items.reduce((n,i)=>n+i.quantity,0)} sản phẩm · {r.orderCode}</small><span>Lý do: {r.reason}</span></div><strong>{money(r.refundAmount)}</strong></div><footer><span>Giá trị dự kiến hoàn</span><a href={'/account/returns/'+r.requestCode}>Xem yêu cầu →</a></footer></article>)}</div>:<div className="orders-empty"><h2>Chưa có yêu cầu hậu mãi</h2><p>Với đơn đã giao/hoàn tất, mở chi tiết đơn để gửi yêu cầu trả hàng.</p><a href="/account/orders">Mở đơn mua</a></div>}</section></div>}
