import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
const require=createRequire(import.meta.url);const ts=require('typescript');
const required=['services/api/src/finance/finance.schema.ts','services/api/src/finance/finance.dto.ts','services/api/src/finance/finance.service.ts','services/api/src/finance/finance.controller.ts','services/api/src/finance/finance.module.ts','apps/seller/components/seller-finance-client.tsx','apps/seller/app/finance/page.tsx','apps/admin/components/admin-finance-client.tsx','apps/admin/app/finance/page.tsx','docs/SELLER_FINANCE.md'];
for(const f of required)if(!fs.existsSync(f)||fs.statSync(f).size<80)throw new Error('Missing/incomplete '+f);
const service=fs.readFileSync('services/api/src/finance/finance.service.ts','utf8'),schema=fs.readFileSync('services/api/src/finance/finance.schema.ts','utf8'),ctl=fs.readFileSync('services/api/src/finance/finance.controller.ts','utf8'),checkout=fs.readFileSync('services/api/src/checkout/checkout.service.ts','utf8'),orders=fs.readFileSync('services/api/src/orders/orders.service.ts','utf8'),returns=fs.readFileSync('services/api/src/returns/returns.service.ts','utf8'),seed=fs.readFileSync('services/api/src/database/seed.ts','utf8');
const checks=[[schema,'SellerLedgerEntry','ledger schema'],[schema,'WithdrawalRequest','withdrawal schema'],[schema,'accountNumberCiphertext','encrypted payout'],[service,"createCipheriv('aes-256-gcm'",'AES-GCM encryption'],[service,'releaseMatured','settlement maturity'],[service,'ACTIVE_WITHDRAWALS','withdrawal holds'],[service,'financeVersion','concurrent withdrawal lock'],[service,'REFUND_DEBIT','refund debit'],[service,'FEE_REVERSAL','commission reversal'],[service,'externalReference','paid reconciliation'],[ctl,"@Controller('seller/finance')",'seller API'],[ctl,"@Controller('admin/finance')",'admin API'],[checkout,'commissionRateBps / 10000','dynamic commission'],[orders,'recordCompletedSubOrders','completion settlement'],[returns,'recordRefund','refund accounting'],[seed,'WD-DEMO-001','finance demo seed']];
for(const [src,tok,label] of checks)if(!src.includes(tok))throw new Error('Missing '+label);
const files=[];for(const root of ['services/api/src','apps/seller','apps/admin']){const walk=d=>{for(const n of fs.readdirSync(d)){const p=path.join(d,n),st=fs.statSync(p);if(st.isDirectory())walk(p);else if(/\.(ts|tsx)$/.test(p)&&!p.endsWith('.d.ts'))files.push(p)}};walk(root)}
for(const f of files){const r=ts.transpileModule(fs.readFileSync(f,'utf8'),{fileName:f,reportDiagnostics:true,compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext,jsx:ts.JsxEmit.ReactJSX,experimentalDecorators:true,emitDecoratorMetadata:true}});for(const d of r.diagnostics??[])if(d.category===ts.DiagnosticCategory.Error)throw new Error(`${f}: ${ts.flattenDiagnosticMessageText(d.messageText,' ')}`)}
console.log(`Finance verification passed: ${required.length} required files, ${checks.length} accounting/security markers, ${files.length} parsed sources.`);
